const esc = (s: unknown) =>
  String(s ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

const PBADGE: Record<number, { emoji: string; label: string; cls: string }> = {
  1: { emoji: "🔴", label: "Priority 1", cls: "p1" },
  2: { emoji: "🟠", label: "Priority 2", cls: "p2" },
  3: { emoji: "🟡", label: "Priority 3", cls: "p3" },
  4: { emoji: "🟢", label: "Priority 4", cls: "p4" },
};

export function priorityBadge(p: number) {
  const b = PBADGE[p] ?? PBADGE[3];
  return `<span class="badge ${b.cls}">${b.emoji} ${b.label}</span>`;
}

export function jsonList(value: unknown, empty = "—"): string {
  const arr = Array.isArray(value) ? (value as string[]) : [];
  if (arr.length === 0) return `<p class="small">${empty}</p>`;
  return `<ul class="tight">${arr.map((v) => `<li>${esc(v)}</li>`).join("")}</ul>`;
}

/** Cell values are trusted HTML (already escaped/composed by the caller). */
export function table(headers: string[], rows: (string | number)[][]) {
  return `<table class="dtable"><tr>${headers.map((h) => `<th>${esc(h)}</th>`).join("")}</tr>
    ${rows.map((r) => `<tr>${r.map((c) => `<td>${c}</td>`).join("")}</tr>`).join("")}</table>`;
}

export function checklist(items: string[]) {
  return `<ul class="checklist">${items.map((i) => `<li>${esc(i)}</li>`).join("")}</ul>`;
}

export function coverPage(kicker: string, title: string, subtitle: string) {
  return `<div class="cover">
    <div><div class="kicker">${esc(kicker)}</div><h1>${esc(title)}</h1><p style="opacity:.9">${esc(subtitle)}</p></div>
    <div class="foot">Generated by Smart Padhai · ${new Date().toLocaleDateString()}</div>
  </div>`;
}

export function chapterCard(c: {
  name: string;
  priority: number;
  importance?: string | null;
  pyqTrend?: unknown;
  mustKnow?: unknown;
  commonMistakes?: unknown;
  questionPatterns?: unknown;
  topics: { name: string; priority: number; description?: string | null }[];
}) {
  const pyq = (c.pyqTrend ?? {}) as { freq?: string; historical?: string; pattern?: string; difficulty?: string };

  return `<div class="chap">
    <div class="chap-head"><span>${esc(c.name)}</span>${priorityBadge(c.priority)}</div>
    <div class="chap-body">
      ${c.importance ? `<span class="lbl">Why this priority</span><p>${esc(c.importance)}</p>` : ""}
      ${pyq.freq ? table(["PYQ frequency", "Historical", "Pattern", "Difficulty"], [[esc(pyq.freq), esc(pyq.historical), esc(pyq.pattern), esc(pyq.difficulty)]]) : ""}
      ${c.topics.length ? `<span class="lbl">Topics</span>${table(["#", "Topic", "Priority", "Notes"], c.topics.map((t, i) => [i + 1, esc(t.name), priorityBadge(t.priority), esc(t.description ?? "")]))}` : ""}
      <div style="display:flex;gap:14px;">
        <div style="flex:1"><span class="lbl">Must know</span>${jsonList(c.mustKnow)}</div>
        <div style="flex:1"><span class="lbl">Common mistakes</span>${jsonList(c.commonMistakes)}</div>
      </div>
      ${c.questionPatterns ? `<span class="lbl">Question patterns to practice</span>${jsonList(c.questionPatterns)}` : ""}
    </div>
  </div>`;
}

export { esc };
