// RBSE Class 12 content data. Sourced from secondary/coaching aggregators (rajeduboard.rajasthan.gov.in
// itself could not be parsed via automated fetch - it is an old frameset site). Every figure here is
// labeled per its confidence tier; conflicting figures are shown as ranges/both-versions, never merged
// into a single invented number.

const PHYSICS = [
 {name:"Electric Charges and Fields", priority:2,
  importance:"Foundational Electrostatics chapter; two independent weightage tables disagree on exact marks (one gives Electrostatics 7/56, another folds it into a broader 'Optics highest' ranking) — treat as consistently moderate-to-high rather than trusting one number.",
  pyq:{freq:"Chapter-wise marks are not permanently fixed and may vary between question papers (Historical/PYQ-based trend only).",historical:"Reported around 7 marks of the 56-mark theory paper in one source; unverified against a second.",pattern:"Coulomb's law numericals, electric field/flux via Gauss's law, dipole in a uniform field.",difficulty:"Moderate."},
  topics:[{name:"Gauss's Law & Applications",priority:1,note:"Field due to infinite sheet/sphere — standard derivation, frequently asked as a 3-4 mark derivation question."},
   {name:"Electric Dipole",priority:2,note:"Field/potential on axial & equatorial line, torque in uniform field — direct-formula question."}],
  mustKnow:["Coulomb's law and superposition principle for multiple charges.","Gauss's law statement and its use for symmetric charge distributions.","Dipole moment p=qd; torque τ=pEsinθ."],
  pyqTypes:["Derive expression for field due to a uniformly charged infinite plane sheet / spherical shell.","Numerical: force/field due to a system of point charges."],
  mistakes:["Sign errors when adding vector fields from multiple charges.","Applying Gauss's law without identifying a valid symmetric Gaussian surface."],
  prereq:[], connected:["Electrostatic Potential & Capacitance","Current Electricity"]},

 {name:"Electrostatic Potential and Capacitance", priority:2,
  importance:"Consistently paired with Electric Charges & Fields in exam weight; capacitor-combination numericals are a reliable, formula-driven scoring area.",
  pyq:{freq:"Chapter-wise marks not officially fixed (Historical/PYQ-based trend only).",historical:"Grouped with Electrostatics at a moderate-high combined weight across sources.",pattern:"Potential due to point charge/dipole, capacitor combination (series/parallel), effect of dielectric.",difficulty:"Moderate."},
  topics:[{name:"Capacitors: Series/Parallel & Energy Stored",priority:1,note:"Equivalent capacitance of networks, energy U=½CV² — very standard numerical."},
   {name:"Potential due to a System of Charges",priority:2,note:"Potential is scalar — direct algebraic addition, unlike field."}],
  mustKnow:["V=kq/r for a point charge; potential due to dipole falls off faster (1/r²) than monopole (1/r).","Parallel plate capacitor C=ε₀A/d; effect of inserting a dielectric slab (partial/full).","Energy density of electric field = ½ε₀E²."],
  pyqTypes:["Numerical on equivalent capacitance of a given network with a dielectric inserted.","Derivation: potential energy of a system of point charges."],
  mistakes:["Treating potential as a vector and adding components instead of scalar addition.","Forgetting energy stored changes differently depending on whether battery stays connected during dielectric insertion."],
  prereq:["Electric Charges and Fields"], connected:["Current Electricity"]},

 {name:"Current Electricity", priority:1,
  importance:"One of the highest, most numerically dense chapters in RBSE Physics; Kirchhoff's law circuits and cell-combination problems are near-guaranteed long-answer/derivation questions.",
  pyq:{freq:"One source reports ~7/56 marks; treat as approximate, not officially fixed.",historical:"Consistently a high-weight chapter in board exams generally for this unit.",pattern:"Kirchhoff's laws circuit numericals, Wheatstone bridge, potentiometer principle, cell grouping.",difficulty:"Moderate-Hard."},
  topics:[{name:"Kirchhoff's Laws & Circuit Numericals",priority:1,note:"Junction and loop law application in multi-loop circuits — standard long-answer numerical."},
   {name:"Wheatstone Bridge & Meter Bridge",priority:1,note:"Balance condition and use to find unknown resistance — frequent derivation+numerical combination."},
   {name:"Potentiometer Principle",priority:2,note:"Comparing EMFs / finding internal resistance using balancing length — standard derivation question."}],
  mustKnow:["Kirchhoff's current law (junction) and voltage law (loop) with correct sign convention.","Wheatstone bridge balance: P/Q = R/S.","Potentiometer: EMF ratio equals balancing-length ratio (no current drawn at balance)."],
  pyqTypes:["Derive the balance condition of a Wheatstone bridge / meter bridge and use it in a numerical.","Multi-loop circuit — apply Kirchhoff's laws to find current in each branch."],
  mistakes:["Wrong loop-traversal sign convention.","Forgetting potentiometer only works correctly when no current is drawn from the cell being measured."],
  prereq:["Electrostatic Potential"], connected:["Moving Charges and Magnetism"]},

 {name:"Moving Charges and Magnetism", priority:2,
  importance:"Frequently tested via Biot-Savart/Ampere's law derivations and force-on-conductor numericals; connects directly to the following chapter (Magnetism and Matter).",
  pyq:{freq:"One source reports ~7/56 marks; unverified against an official blueprint.",historical:"Stable moderate-high across general board-pattern sources.",pattern:"Biot-Savart law derivation for a circular loop, force between two parallel currents, moving-coil galvanometer.",difficulty:"Moderate."},
  topics:[{name:"Biot-Savart Law & Field of a Circular Loop",priority:1,note:"Field at the centre and on the axis — standard derivation question."},
   {name:"Force Between Two Parallel Conductors",priority:2,note:"Used to define the ampere — derivation + numerical."}],
  mustKnow:["Biot-Savart law formula and right-hand rule for direction.","Ampere's circuital law and its use for a straight wire/solenoid.","Moving-coil galvanometer construction and current sensitivity."],
  pyqTypes:["Derive the magnetic field at the centre of a current-carrying circular loop.","Numerical: force per unit length between two long parallel current-carrying wires."],
  mistakes:["Incorrect direction from the right-hand rule.","Confusing Ampere's law application region (inside vs outside a solenoid/wire)."],
  prereq:["Current Electricity"], connected:["Magnetism and Matter","Electromagnetic Induction"]},

 {name:"Magnetism and Matter", priority:3,
  importance:"Smaller, mostly factual/derivation chapter (Earth's magnetism, magnetic properties of materials) — moderate weight, efficient to revise close to the exam.",
  pyq:{freq:"Chapter-wise marks not officially fixed.",historical:"Generally a lighter-weight chapter relative to Current Electricity/Magnetism-effects.",pattern:"Bar magnet as an equivalent solenoid, Earth's magnetic elements, dia/para/ferromagnetic classification.",difficulty:"Easy-Moderate."},
  topics:[{name:"Bar Magnet & Earth's Magnetism",priority:1,note:"Magnetic elements (declination, inclination, horizontal component) — factual + short numerical."},
   {name:"Classification of Magnetic Materials",priority:2,note:"Dia/para/ferromagnetic properties and examples — direct factual question."}],
  mustKnow:["Magnetic dipole moment of a bar magnet and its field along axial/equatorial lines.","Three elements of Earth's magnetic field.","Curie temperature concept for ferromagnetic materials."],
  pyqTypes:["Short-answer: distinguish dia/para/ferromagnetic substances with examples.","Numerical on the field of a bar magnet at an axial/equatorial point."],
  mistakes:["Confusing declination and inclination definitions.","Mixing up which classification a given material (e.g., aluminium, copper, iron) belongs to."],
  prereq:["Moving Charges and Magnetism"], connected:["Electromagnetic Induction"]},

 {name:"Electromagnetic Induction", priority:2,
  importance:"Faraday's/Lenz's law derivations and induced-EMF numericals are a reliable, frequently-tested area shared conceptually with JEE Main.",
  pyq:{freq:"Chapter-wise marks not officially fixed.",historical:"Moderate-high, stable across general board patterns.",pattern:"EMF induced in a rotating coil/moving rod, self and mutual inductance, eddy currents.",difficulty:"Moderate."},
  topics:[{name:"Faraday's & Lenz's Laws",priority:1,note:"Induced EMF direction and magnitude in a changing-flux scenario — standard derivation+numerical."},
   {name:"Self & Mutual Inductance",priority:2,note:"L of a solenoid; energy stored in an inductor — direct-formula numerical."}],
  mustKnow:["EMF=-dΦ/dt; Lenz's law gives direction opposing the change in flux.","Self-inductance of a long solenoid formula.","Eddy currents and their practical applications/disadvantages."],
  pyqTypes:["Derive EMF induced in a rod moving on rails in a magnetic field.","Numerical: energy stored in an inductor / mutual inductance between two coils."],
  mistakes:["Sign errors applying Lenz's law.","Confusing self-inductance and mutual-inductance formulas."],
  prereq:["Moving Charges and Magnetism"], connected:["Alternating Current"]},

 {name:"Alternating Current", priority:2,
  importance:"LCR circuit and transformer numericals are dependable, formula-driven marks; resonance-condition questions recur often.",
  pyq:{freq:"One source reports ~9/56 marks for EMI+AC combined; unverified split between the two.",historical:"Moderate-high combined with EMI.",pattern:"LCR series circuit impedance/resonance, transformer working & efficiency, AC generator principle.",difficulty:"Moderate."},
  topics:[{name:"LCR Series Circuit & Resonance",priority:1,note:"Impedance, resonant frequency, power factor — standard numerical."},
   {name:"Transformer",priority:2,note:"Step-up/step-down working, turns ratio, energy losses — factual + numerical."}],
  mustKnow:["Impedance Z=√(R²+(XL-XC)²); resonance when XL=XC.","Transformer equation Vs/Vp=Ns/Np (ideal case).","Power factor cosφ and its significance for power consumed."],
  pyqTypes:["Derive/compute impedance and current in a given LCR series circuit.","Numerical on transformer turns ratio and output voltage/current."],
  mistakes:["Forgetting AC values used are RMS unless stated otherwise.","Sign/phase errors in the impedance triangle."],
  prereq:["Electromagnetic Induction"], connected:["Electromagnetic Waves"]},

 {name:"Electromagnetic Waves", priority:3,
  importance:"Small, mostly factual chapter on the EM spectrum and displacement current — low derivation burden, efficient last-minute revision.",
  pyq:{freq:"Chapter-wise marks not officially fixed; generally one of the lighter chapters.",historical:"Consistently smaller weight than core Electrodynamics/Optics chapters.",pattern:"EM spectrum order and uses, displacement current concept, properties of EM waves.",difficulty:"Easy."},
  topics:[{name:"EM Spectrum & Uses",priority:1,note:"Order by wavelength/frequency and practical application of each band — direct factual question."}],
  mustKnow:["EM waves are transverse and require no medium.","Displacement current concept — why Ampere's law needed modification.","c=1/√(μ₀ε₀); E₀=cB₀."],
  pyqTypes:["Short-answer: name the EM spectrum bands in order with one use each.","Conceptual question on displacement current."],
  mistakes:["Wrong order of the EM spectrum by wavelength/frequency/energy.","Confusing displacement current with conduction current."],
  prereq:["Alternating Current"], connected:["Ray Optics and Optical Instruments"]},

 {name:"Ray Optics and Optical Instruments", priority:1,
  importance:"One source flags Optics as the single highest-weight Physics chapter (12/56 marks) — the most reliably high-value chapter in RBSE Physics; lens/mirror derivations and optical-instrument (microscope/telescope) numericals recur heavily.",
  pyq:{freq:"Reported ~12/56 marks in one source — highest of any Physics chapter found (Historical/PYQ-based trend, not officially confirmed).",historical:"Consistently flagged as top-weight across general board-pattern sources.",pattern:"Lens/mirror formula derivations, refraction through prism, compound microscope/telescope magnifying power.",difficulty:"Moderate."},
  topics:[{name:"Lens & Mirror Formula, Magnification",priority:1,note:"Image formation numericals with sign convention — very frequent."},
   {name:"Refraction Through a Prism",priority:1,note:"Angle of deviation, minimum deviation condition, refractive index — standard derivation."},
   {name:"Optical Instruments (microscope, telescope)",priority:1,note:"Magnifying power formulas for compound microscope & astronomical telescope — recurring derivation question."}],
  mustKnow:["Mirror/lens formula and lensmaker's equation with sign convention.","Magnifying power of simple/compound microscope and telescope (normal adjustment).","Prism formula: A+δ=i+e; minimum deviation condition i=e."],
  pyqTypes:["Derive magnifying power of a compound microscope/astronomical telescope.","Numerical: image formed by a combination of lenses or through a prism."],
  mistakes:["Sign convention slips (Cartesian convention direction).","Confusing magnifying power formulas for normal adjustment vs least distance of distinct vision."],
  prereq:["Electromagnetic Waves (conceptual)"], connected:["Wave Optics"]},

 {name:"Wave Optics", priority:2,
  importance:"YDSE and diffraction numericals are standard, formula-driven marks and directly overlap with JEE Main preparation.",
  pyq:{freq:"Chapter-wise marks not officially fixed; generally paired with Ray Optics for high combined weight.",historical:"Moderate-high, stable.",pattern:"Young's double slit fringe width, diffraction minima condition, polarisation basics.",difficulty:"Moderate."},
  topics:[{name:"Young's Double Slit Experiment",priority:1,note:"Fringe width formula and effect of changing wavelength/slit separation — standard numerical."},
   {name:"Diffraction & Polarisation",priority:2,note:"Single-slit diffraction minima, Malus's law — factual + light numerical."}],
  mustKnow:["Fringe width β=λD/d.","Condition for constructive/destructive interference (path difference nλ / (n+½)λ).","Malus's law I=I₀cos²θ for polarised light through an analyser."],
  pyqTypes:["Derive expression for fringe width in YDSE.","Numerical on change in fringe pattern when a parameter (λ, d, D) changes."],
  mistakes:["Confusing diffraction minima condition with interference maxima condition.","Forgetting polarisation only applies to transverse waves."],
  prereq:["Ray Optics and Optical Instruments"], connected:["Dual Nature of Radiation and Matter"]},

 {name:"Dual Nature of Radiation and Matter", priority:2,
  importance:"Photoelectric effect numericals are formulaic and a reliable scoring area, directly overlapping with JEE Main preparation.",
  pyq:{freq:"Chapter-wise marks not officially fixed.",historical:"Moderate-high, part of the Modern Physics group.",pattern:"Einstein's photoelectric equation, stopping potential, de Broglie wavelength.",difficulty:"Moderate."},
  topics:[{name:"Photoelectric Effect",priority:1,note:"Einstein's equation, threshold frequency, stopping potential graph — standard derivation+numerical."},
   {name:"de Broglie Wavelength",priority:1,note:"λ=h/p, applied to accelerated electrons — frequent numerical."}],
  mustKnow:["KEmax=hν-φ₀; graph of stopping potential vs frequency gives slope h/e.","de Broglie wavelength formula and its dependence on accelerating voltage for electrons.","Photoelectric current depends on intensity; KEmax depends only on frequency."],
  pyqTypes:["Derive/apply Einstein's photoelectric equation in a numerical.","Numerical on de Broglie wavelength of an accelerated particle."],
  mistakes:["Mixing up which quantity (current vs KEmax) depends on intensity vs frequency.","Unit conversion errors between eV and joules."],
  prereq:["Wave Optics","Atoms"], connected:["Atoms","Nuclei"]},

 {name:"Atoms", priority:2,
  importance:"Bohr model numericals (energy levels, spectral lines) are formulaic and a dependable scoring chapter, overlapping directly with JEE Main.",
  pyq:{freq:"Chapter-wise marks not officially fixed.",historical:"Moderate-high, part of the Modern Physics group.",pattern:"Bohr model energy/radius, hydrogen spectrum line series, Rutherford's model limitations.",difficulty:"Moderate."},
  topics:[{name:"Bohr Model of Hydrogen Atom",priority:1,note:"Energy levels En=-13.6/n² eV, spectral series (Lyman/Balmer/Paschen) — standard derivation+numerical."}],
  mustKnow:["Bohr's postulates and derivation of energy/radius formulas.","Rydberg formula for spectral line wavelength.","Limitations of Rutherford's model that Bohr's model addressed."],
  pyqTypes:["Derive the expression for energy of an electron in the nth orbit of hydrogen atom.","Numerical: wavelength of a spectral line for a given transition."],
  mistakes:["Sign errors in energy formula (bound state energy is negative).","Confusing which series (Lyman/Balmer/Paschen) corresponds to which final energy level."],
  prereq:["Dual Nature of Radiation and Matter"], connected:["Nuclei"]},

 {name:"Nuclei", priority:2,
  importance:"Radioactive decay-law numericals and binding energy questions are formulaic and directly overlap with JEE Main.",
  pyq:{freq:"Chapter-wise marks not officially fixed.",historical:"Moderate-high, part of the Modern Physics group.",pattern:"Half-life/decay-law numericals, binding energy per nucleon, nuclear fission/fusion energy release.",difficulty:"Moderate."},
  topics:[{name:"Radioactive Decay Law",priority:1,note:"N=N₀e^(-λt), half-life relation — standard numerical."},
   {name:"Binding Energy & Mass Defect",priority:2,note:"BE=Δmc²; fission/fusion energy release reasoning — conceptual + numerical."}],
  mustKnow:["T½=ln2/λ; activity A=λN.","Binding energy per nucleon curve shape and its implication for fission (heavy nuclei) vs fusion (light nuclei).","Mass-energy equivalence E=mc² applied to nuclear reactions."],
  pyqTypes:["Numerical on remaining quantity of a radioactive sample after a given time/number of half-lives.","Numerical: energy released in a given fission/fusion reaction using mass defect."],
  mistakes:["Confusing half-life with mean life.","Arithmetic errors converting atomic mass unit to energy (1u=931.5 MeV)."],
  prereq:["Atoms"], connected:["Semiconductor Electronics"]},

 {name:"Semiconductor Electronics", priority:2,
  importance:"p-n junction diode and rectifier questions are conceptually light but frequently tested, with strong JEE Main overlap.",
  pyq:{freq:"Chapter-wise marks not officially fixed.",historical:"Moderate weight, stable.",pattern:"p-n junction working, rectifier circuits, zener diode as voltage regulator, logic gates.",difficulty:"Easy-Moderate."},
  topics:[{name:"p-n Junction Diode & Rectifiers",priority:1,note:"Forward/reverse bias, half-wave/full-wave rectification — standard conceptual+circuit question."},
   {name:"Logic Gates",priority:2,note:"Truth tables for basic and combination gates — direct factual question."}],
  mustKnow:["Diode behaviour in forward vs reverse bias.","Full-wave rectifier circuit and output waveform.","Truth tables for AND, OR, NOT, NAND, NOR gates."],
  pyqTypes:["Explain working of a full-wave rectifier with circuit diagram and waveform.","Truth-table based question on a combination of logic gates."],
  mistakes:["Reversing bias direction convention in circuit diagrams.","Truth-table sign errors for NAND/NOR (negation of AND/OR)."],
  prereq:["Nuclei (band theory, conceptual)","Current Electricity"], connected:["Current Electricity"]},
];

const CHEMISTRY = [
 {name:"Solid State", priority:3,
  importance:"Factual/geometry-based chapter (unit cell types, packing efficiency); not included in the specific 56-mark weightage table found in research, suggesting lighter direct weight than the organic chapters — but remains part of the syllabus and appears in most years.",
  pyq:{freq:"Insufficient verified data for an exact frequency — this chapter was absent from the one self-consistent weightage table found in research.",historical:"Generally a lighter-weight chapter relative to Organic Chemistry.",pattern:"Packing efficiency calculation, types of unit cells (SCC/BCC/FCC), point defects.",difficulty:"Easy-Moderate."},
  topics:[{name:"Packing Efficiency & Unit Cell Calculations",priority:1,note:"Number of atoms per unit cell, packing efficiency for SCC/BCC/FCC — standard numerical."},
   {name:"Point Defects",priority:2,note:"Schottky vs Frenkel defect — factual comparison question."}],
  mustKnow:["Atoms per unit cell: SCC=1, BCC=2, FCC=4.","Packing efficiency: SCC 52.4%, BCC 68%, FCC 74%.","Schottky defect (ions missing, density decreases) vs Frenkel defect (ion displaced, density unchanged)."],
  pyqTypes:["Numerical: calculate density of a crystal given unit cell edge length and type.","Distinguish Schottky and Frenkel defects with examples."],
  mistakes:["Wrong atoms-per-unit-cell count (forgetting corner/face/edge contribution fractions).","Confusing which defect changes density."],
  prereq:[], connected:["Solutions"]},

 {name:"Solutions", priority:2,
  importance:"Reported at 6/56 marks in the most self-consistent weightage table found — colligative property numericals are formula-driven and reliable marks.",
  pyq:{freq:"~6 marks of the 56-mark theory paper (Historical/PYQ-based trend from one aggregator source — treat as plausible, not officially confirmed).",historical:"Moderate-high, stable.",pattern:"Colligative properties (elevation/depression), Raoult's law, van't Hoff factor.",difficulty:"Moderate."},
  topics:[{name:"Colligative Properties",priority:1,note:"ΔTb, ΔTf, osmotic pressure numericals — very standard."},
   {name:"van't Hoff Factor",priority:2,note:"Degree of association/dissociation from observed vs calculated colligative property."}],
  mustKnow:["ΔTb=iKbm, ΔTf=iKfm, π=iCRT.","Raoult's law and positive/negative deviation from ideal behaviour.","van't Hoff factor >1 for dissociation, <1 for association."],
  pyqTypes:["Numerical: find molar mass of a solute from depression in freezing point.","Numerical involving van't Hoff factor for an electrolyte solution."],
  mistakes:["Forgetting van't Hoff factor correction for electrolytes.","Using wrong solvent constant (Kb vs Kf) for the property asked."],
  prereq:["Solid State"], connected:["Electrochemistry"]},

 {name:"Electrochemistry", priority:2,
  importance:"Reported at 6/56 marks — Nernst equation and electrolysis numericals are dependable, formula-driven marks with strong JEE Main overlap.",
  pyq:{freq:"~6 marks of the 56-mark theory paper (Historical/PYQ-based trend, one source).",historical:"Moderate-high, stable.",pattern:"Nernst equation for cell EMF, Faraday's laws of electrolysis, conductance.",difficulty:"Moderate."},
  topics:[{name:"Nernst Equation & EMF of a Cell",priority:1,note:"Cell EMF under non-standard conditions — standard numerical."},
   {name:"Faraday's Laws of Electrolysis",priority:1,note:"Mass deposited from charge passed — direct-substitution numerical."}],
  mustKnow:["Nernst equation E=E°-(0.0591/n)logQ.","Faraday's first law: w=ZIt=(M/nF)It.","ΔG°=-nFE°cell links thermodynamics and electrochemistry."],
  pyqTypes:["Numerical: EMF of a galvanic cell given electrode potentials and concentrations.","Numerical: mass of substance deposited during electrolysis for a given current and time."],
  mistakes:["Sign errors in cell EMF/Nernst equation direction.","Forgetting number of electrons transferred (n) when applying Faraday's law."],
  prereq:["Solutions"], connected:["Chemical Kinetics"]},

 {name:"Chemical Kinetics", priority:2,
  importance:"Reported at 6/56 marks — integrated rate law and half-life numericals for first-order reactions are formula-driven and time-efficient.",
  pyq:{freq:"~6 marks of the 56-mark theory paper (Historical/PYQ-based trend, one source).",historical:"Moderate-high, stable.",pattern:"Order of reaction determination, integrated rate law numericals, Arrhenius equation.",difficulty:"Moderate."},
  topics:[{name:"Integrated Rate Law & Half-life",priority:1,note:"First-order half-life independent of concentration — standard numerical."},
   {name:"Arrhenius Equation",priority:2,note:"Activation energy from rate constants at two temperatures — log-based numerical."}],
  mustKnow:["First-order: k=(2.303/t)log(a/a-x); t½=0.693/k.","Rate law is experimentally determined, not assumed from stoichiometry.","Arrhenius: k=Ae^(-Ea/RT)."],
  pyqTypes:["Numerical: find rate constant/order from given concentration-time data.","Numerical: activation energy from rate constants at two different temperatures."],
  mistakes:["Assuming reaction order from stoichiometric coefficients without verification.","Log-base/2.303-factor errors in first-order calculations."],
  prereq:["Electrochemistry (rate-equilibrium link, conceptual)"], connected:["Surface Chemistry"]},

 {name:"Surface Chemistry", priority:3,
  importance:"Mostly factual chapter (adsorption, catalysis, colloids); not present in the specific weightage table found, suggesting comparatively lighter direct weight, though it remains part of the prescribed syllabus.",
  pyq:{freq:"Insufficient verified data for an exact frequency.",historical:"Generally a lighter-weight, factual chapter.",pattern:"Types of adsorption (physisorption vs chemisorption), Freundlich isotherm, types of colloids.",difficulty:"Easy."},
  topics:[{name:"Adsorption & Catalysis",priority:1,note:"Physisorption vs chemisorption distinguishing features — factual comparison question."},
   {name:"Colloids",priority:2,note:"Classification (sol, gel, emulsion) and properties (Tyndall effect, electrophoresis) — factual recall."}],
  mustKnow:["Physisorption: weak van der Waals forces, reversible, decreases with temperature rise; chemisorption: strong chemical bonds, irreversible.","Freundlich adsorption isotherm: x/m=kP^(1/n).","Tyndall effect distinguishes colloids from true solutions."],
  pyqTypes:["Distinguish physisorption and chemisorption with examples.","Short-answer: explain any two properties of colloidal solutions."],
  mistakes:["Mixing up which adsorption type is reversible.","Confusing colloid classification (dispersed phase/medium combinations)."],
  prereq:["Chemical Kinetics"], connected:["Isolation of Elements (industrial catalysis link)"]},

 {name:"General Principles and Processes of Isolation of Elements", priority:3,
  importance:"Applied/factual Inorganic chapter (metallurgy); moderate weight, mostly definitional and process-based questions.",
  pyq:{freq:"Insufficient verified data for an exact frequency.",historical:"Generally moderate, stable factual chapter.",pattern:"Ore concentration methods, extraction process for a named metal (e.g., aluminium, iron, copper), refining methods.",difficulty:"Easy-Moderate."},
  topics:[{name:"Extraction Processes for Named Metals",priority:1,note:"Aluminium (Hall-Héroult), iron (blast furnace), copper extraction steps — factual sequence question."}],
  mustKnow:["Concentration methods: gravity separation, froth flotation, magnetic separation, leaching.","Thermodynamic principle of extraction (Ellingham diagram concept, qualitative).","Refining methods: electrolytic refining, zone refining, vapour-phase refining."],
  pyqTypes:["Describe the extraction process of a named metal with reactions.","Short-answer: name and explain a concentration/refining method."],
  mistakes:["Mixing up which method suits sulphide vs oxide ores.","Confusing refining method names with their correct application."],
  prereq:["Surface Chemistry (catalysis, conceptual)"], connected:["p-Block Elements","d- and f-Block Elements"]},

 {name:"p-Block Elements", priority:3,
  importance:"Descriptive Inorganic chapter (groups 15-18); not present in the specific 56-mark weightage table found, but remains a substantial, fact-heavy part of the syllabus.",
  pyq:{freq:"Insufficient verified data for an exact frequency in the current blueprint.",historical:"Traditionally a high-content, fact-heavy chapter in board-level Inorganic Chemistry.",pattern:"Preparation and properties of named compounds (ammonia, nitric acid, sulfuric acid), oxoacid structures, group trends.",difficulty:"Moderate."},
  topics:[{name:"Preparation & Properties of Named Compounds",priority:1,note:"Ostwald's process (nitric acid), Contact process (sulfuric acid) — factual process question."},
   {name:"Oxoacid Structures & Group Trends",priority:2,note:"Structures of oxoacids of phosphorus/sulfur, anomalous behaviour of first group member — structure-based question."}],
  mustKnow:["Industrial preparation reactions for ammonia (Haber), nitric acid (Ostwald), sulfuric acid (Contact process).","Anomalous behaviour of nitrogen/oxygen/fluorine vs their group.","Oxoacid structures via VSEPR for phosphorus and sulfur compounds."],
  pyqTypes:["Write reactions/conditions for an industrial preparation process of a named p-block compound.","Draw/explain the structure of a given oxoacid."],
  mistakes:["Missing correct catalyst/conditions in named industrial processes.","Incorrect oxidation state assignment when drawing oxoacid structures."],
  prereq:["Isolation of Elements","Chemical Bonding (Class 11 basics)"], connected:["d- and f-Block Elements"]},

 {name:"d- and f-Block Elements", priority:2,
  importance:"Reported at 5/56 marks — variable oxidation states and colour/magnetic property reasoning are recurring, moderate-length answer questions.",
  pyq:{freq:"~5 marks of the 56-mark theory paper (Historical/PYQ-based trend, one source).",historical:"Moderate, stable.",pattern:"Variable oxidation states, colour due to d-d transition, magnetic moment, lanthanide contraction.",difficulty:"Moderate."},
  topics:[{name:"Variable Oxidation States & Colour",priority:1,note:"Explain colour via incomplete d-subshell; highest oxidation state trend — reasoning question."},
   {name:"Magnetic Properties",priority:2,note:"Spin-only formula from unpaired electron count — direct numerical."}],
  mustKnow:["Colour arises from d-d electronic transitions (needs partially filled d-orbitals); Sc³⁺/Zn²⁺ are colourless.","Spin-only magnetic moment μ=√n(n+2) BM.","Lanthanide contraction and its effect on radii/basicity of lanthanides."],
  pyqTypes:["Explain why transition metal ions are generally coloured, with an exception.","Numerical: find magnetic moment of a given transition metal ion."],
  mistakes:["Forgetting to determine correct oxidation state before counting d-electrons.","Assuming all transition ions are coloured without checking d-electron count."],
  prereq:["p-Block Elements"], connected:["Coordination Compounds"]},

 {name:"Coordination Compounds", priority:1,
  importance:"Reported at 5/56 marks in the direct weightage table but consistently flagged among the most conceptually rich, exam-favoured Inorganic chapters (also a JEE Main top chapter) — IUPAC naming and CFT questions recur heavily.",
  pyq:{freq:"~5 marks of the 56-mark theory paper (Historical/PYQ-based trend, one source) — likely under-representing true importance given repeated derivation/naming questions reported generally.",historical:"Consistently significant across general board-pattern sources; also a top JEE Main chapter (see Section 14 overlap).",pattern:"IUPAC nomenclature, isomerism, Crystal Field Theory (CFT) — colour and magnetism.",difficulty:"Moderate-Hard."},
  topics:[{name:"IUPAC Nomenclature",priority:1,note:"Naming complex ions/compounds with correct ligand order — direct question."},
   {name:"Crystal Field Theory",priority:1,note:"d-orbital splitting, high-spin/low-spin, CFSE — standard reasoning+numerical."},
   {name:"Isomerism in Coordination Compounds",priority:2,note:"Geometrical and optical isomerism identification — direct question."}],
  mustKnow:["Spectrochemical series determines strong-field (low-spin) vs weak-field (high-spin) ligands.","CFT splitting pattern in octahedral vs tetrahedral fields.","IUPAC naming rules: ligands alphabetically, anionic ligand suffix '-o', oxidation state in Roman numerals."],
  pyqTypes:["Write the IUPAC name of a given coordination compound.","Explain the colour/magnetic behaviour of a given complex using CFT."],
  mistakes:["Wrong ligand-naming order or missing anionic-ligand suffix.","Confusing octahedral vs tetrahedral splitting pattern direction."],
  prereq:["d- and f-Block Elements","Chemical Bonding"], connected:["d- and f-Block Elements"]},

 {name:"Haloalkanes and Haloarenes", priority:2,
  importance:"Reported at 6/56 marks — SN1/SN2 mechanism reasoning is a reliable, frequently tested organic topic.",
  pyq:{freq:"~6 marks of the 56-mark theory paper (Historical/PYQ-based trend, one source).",historical:"Moderate-high, stable.",pattern:"SN1 vs SN2 mechanism conditions, preparation methods, Grignard reagent reactions.",difficulty:"Moderate."},
  topics:[{name:"SN1 vs SN2 Mechanism",priority:1,note:"Substrate/nucleophile/solvent dependence and stereochemical outcome — standard comparison question."}],
  mustKnow:["SN2: 1° substrate, strong nucleophile, inversion of configuration.","SN1: 3° substrate, carbocation intermediate, racemisation.","Grignard reagents must be prepared and used under anhydrous conditions."],
  pyqTypes:["Distinguish SN1 and SN2 mechanisms with an example each.","Write the product and mechanism for a given haloalkane reaction."],
  mistakes:["Forgetting solvent polarity's role in determining SN1 vs SN2 preference.","Grignard reagent reacting with moisture instead of the intended electrophile in written mechanisms."],
  prereq:["General organic chemistry basics (Class 11)"], connected:["Alcohols, Phenols and Ethers"]},

 {name:"Alcohols, Phenols and Ethers", priority:2,
  importance:"Reported at 6/56 marks — distinguishing tests (Lucas reagent) and acidity-order reasoning are dependable, recurring question types.",
  pyq:{freq:"~6 marks of the 56-mark theory paper (Historical/PYQ-based trend, one source).",historical:"Moderate-high, stable.",pattern:"Lucas test for alcohols, relative acidity of phenol/alcohol, Williamson ether synthesis.",difficulty:"Moderate."},
  topics:[{name:"Distinguishing Tests & Acidity Order",priority:1,note:"Lucas test order (3°>2°>1°); phenol more acidic than alcohol due to resonance-stabilised phenoxide — standard reasoning question."}],
  mustKnow:["Lucas test turbidity-time order for 1°/2°/3° alcohols.","Phenoxide ion resonance stabilisation explains phenol's higher acidity vs alcohols.","Williamson synthesis limitation with tertiary alkyl halides (elimination competes)."],
  pyqTypes:["Distinguish a given pair of alcohols/phenols using a named test.","Explain why phenol is more acidic than ethanol (resonance-based reasoning)."],
  mistakes:["Forgetting substituent effect on phenol acidity (EWG increases, EDG decreases).","Wrong turbidity-time order in Lucas test explanation."],
  prereq:["Haloalkanes and Haloarenes"], connected:["Aldehydes, Ketones and Carboxylic Acids"]},

 {name:"Aldehydes, Ketones and Carboxylic Acids", priority:1,
  importance:"Reported as the single highest-weightage Chemistry chapter (7/56 marks) in the most self-consistent weightage table found — nucleophilic addition and named-reaction questions are dense and highly examinable.",
  pyq:{freq:"~7/56 marks — highest of any Chemistry chapter found (Historical/PYQ-based trend, one source, internally consistent with total).",historical:"Consistently significant; also a top JEE Main organic chapter (see Section 14 overlap).",pattern:"Nucleophilic addition reactivity, named reactions (Aldol, Cannizzaro, Haloform), carboxylic acid derivative reactions.",difficulty:"Moderate-Hard."},
  topics:[{name:"Named Reactions: Aldol, Cannizzaro, Haloform",priority:1,note:"Conditions required for each (α-H needed for Aldol/Haloform; none for Cannizzaro) — product-prediction question."},
   {name:"Nucleophilic Addition Reactivity Order",priority:1,note:"HCHO>aldehydes>ketones — direct reasoning + numerical."}],
  mustKnow:["Cannizzaro reaction requires NO α-hydrogen (self redox to alcohol+acid).","Haloform reaction requires a methyl ketone or ethanol-type structure.","Carboxylic acid acidity order and conversion to acid chloride/ester/amide derivatives."],
  pyqTypes:["Identify which of several carbonyl compounds undergoes Cannizzaro/Aldol and write the product.","Multi-step conversion: given a carbonyl compound, write the sequence to reach a target product."],
  mistakes:["Applying Aldol conditions to a compound lacking α-hydrogen (should be Cannizzaro instead).","Reactivity-order errors ignoring steric hindrance in ketones."],
  prereq:["Alcohols, Phenols and Ethers"], connected:["Amines","Biomolecules"]},

 {name:"Amines", priority:2,
  importance:"Reported at 5/56 marks — basicity-order and diazonium-salt reaction questions recur reliably.",
  pyq:{freq:"~5 marks of the 56-mark theory paper (Historical/PYQ-based trend, one source).",historical:"Moderate, stable.",pattern:"Basicity order of amines, diazonium salt reactions (Sandmeyer, coupling).",difficulty:"Moderate."},
  topics:[{name:"Basicity Order & Diazonium Salt Reactions",priority:1,note:"Aqueous-phase basicity order nuance; Sandmeyer/coupling product prediction — standard reasoning+application question."}],
  mustKnow:["Aromatic amine basicity lowered by resonance delocalisation into the ring.","Aqueous basicity order for methylamines: 2°>1°>3°>NH3 (solvation effect).","Diazonium salts stable only at low temperature (0-5°C)."],
  pyqTypes:["Rank a set of amines by basicity with reasoning.","Write the product of a diazonium salt with a given reagent (Sandmeyer/coupling)."],
  mistakes:["Using only inductive-effect logic for aqueous basicity order.","Forgetting the low-temperature condition for diazonium salt formation/reactions."],
  prereq:["Haloalkanes and Haloarenes"], connected:["Biomolecules"]},

 {name:"Biomolecules", priority:3,
  importance:"Reported as the lowest-weightage chapter in the specific table found (4/56 marks) — mostly factual/descriptive, low calculation burden.",
  pyq:{freq:"~4/56 marks — lowest of any Chemistry chapter in the table found (Historical/PYQ-based trend, one source).",historical:"Consistently a lighter, mostly-factual chapter.",pattern:"Classification of carbohydrates, protein structure levels, vitamin deficiency diseases, DNA/RNA differences.",difficulty:"Easy."},
  topics:[{name:"Carbohydrates & Proteins",priority:1,note:"Reducing vs non-reducing sugars; levels of protein structure — factual recall question."},
   {name:"Vitamins & Nucleic Acids",priority:2,note:"Deficiency diseases; DNA vs RNA differences — direct factual question."}],
  mustKnow:["Reducing sugars have a free anomeric group; sucrose is non-reducing.","Denaturation destroys secondary/tertiary protein structure, not primary.","DNA: deoxyribose+thymine; RNA: ribose+uracil."],
  pyqTypes:["Match vitamins to deficiency diseases.","Distinguish DNA and RNA in terms of sugar and base composition."],
  mistakes:["Confusing fat-soluble vs water-soluble vitamin classification.","Mixing up DNA/RNA base differences."],
  prereq:["Aldehydes, Ketones and Carboxylic Acids"], connected:["General organic reasoning"]},

 {name:"Polymers", priority:3,
  importance:"Factual chapter on classification and named polymers; not present in the specific weightage table found, suggesting lighter direct weight, but remains part of the syllabus.",
  pyq:{freq:"Insufficient verified data for an exact frequency.",historical:"Generally a lighter, factual chapter.",pattern:"Classification (addition vs condensation), named polymers and their monomers, natural vs synthetic rubber.",difficulty:"Easy."},
  topics:[{name:"Classification & Named Polymers",priority:1,note:"Monomer-to-polymer matching for common polymers (nylon-6,6, PET, Bakelite) — direct factual question."}],
  mustKnow:["Addition polymers (from unsaturated monomers) vs condensation polymers (with elimination of small molecule).","Common polymer-monomer pairs and one industrial use each.","Vulcanisation improves rubber's elasticity/strength."],
  pyqTypes:["Match a named polymer to its monomer(s) and classify it.","Short-answer on vulcanisation of rubber."],
  mistakes:["Mixing up addition vs condensation classification for a given polymer.","Incorrect monomer units for well-known polymers."],
  prereq:["Aldehydes, Ketones and Carboxylic Acids"], connected:["Biomolecules"]},

 {name:"Chemistry in Everyday Life", priority:4,
  importance:"Purely factual/definitional chapter (drugs, cleansing agents); not present in the specific weightage table found, suggesting the lightest direct weight of any Chemistry chapter.",
  pyq:{freq:"Insufficient verified data for an exact frequency.",historical:"Consistently the lightest-weight chapter where included.",pattern:"Classification of drugs by target/action, soaps vs detergents, food preservatives/artificial sweeteners.",difficulty:"Easy."},
  topics:[{name:"Drugs & Cleansing Agents",priority:1,note:"Antacid/antihistamine/analgesic classification; soap vs synthetic detergent structure — factual recall question."}],
  mustKnow:["Drug classification by biological target (receptor-based) vs by pharmacological action.","Soaps are Na/K salts of fatty acids; detergents work even in hard water.","Common examples of antibiotics, analgesics, antiseptics with one use each."],
  pyqTypes:["Match drug categories to examples and their use.","Short-answer distinguishing soap and synthetic detergent."],
  mistakes:["Confusing antiseptic and disinfectant definitions.","Mixing up narrow-spectrum vs broad-spectrum antibiotic examples."],
  prereq:["Biomolecules","Polymers"], connected:[]},
];

const MATH = [
 {name:"Relations and Functions", priority:2,
  importance:"Reported at 7/80 marks; foundational unit whose function-property reasoning underlies the whole Calculus block that follows.",
  pyq:{freq:"~7 of 80 theory marks (Historical/PYQ-based trend — reasonably corroborated across 2 aggregator sources for the unit-wise split).",historical:"Stable moderate weight.",pattern:"Types of relations (equivalence relation proof), function properties (one-one/onto), inverse trigonometric function simplification.",difficulty:"Moderate."},
  topics:[{name:"Equivalence Relations",priority:1,note:"Prove reflexive+symmetric+transitive for a given relation — standard proof-style question."},
   {name:"Inverse Trigonometric Functions",priority:1,note:"Simplify/evaluate compound inverse-trig expressions using principal value branches — recurring question type."}],
  mustKnow:["Equivalence relation requires all three properties checked explicitly.","Principal value branches for sin⁻¹, cos⁻¹, tan⁻¹.","A function is invertible iff bijective."],
  pyqTypes:["Prove a given relation is (or is not) an equivalence relation.","Simplify a given inverse trigonometric expression to its simplest form."],
  mistakes:["Skipping one of the three equivalence-relation properties in a proof.","Using the wrong principal-value branch when simplifying inverse-trig expressions."],
  prereq:[], connected:["Calculus block (Continuity, Differentiability)"]},

 {name:"Algebra (Matrices & Determinants)", priority:2,
  importance:"Reported at 10/80 marks; inverse-matrix and system-of-equations numericals are formula-driven and dependable marks, with strong JEE Main overlap.",
  pyq:{freq:"~10 of 80 theory marks (Historical/PYQ-based trend, reasonably corroborated).",historical:"Stable moderate-high weight.",pattern:"Finding inverse via adjoint, solving a system of equations by matrix method, properties of determinants.",difficulty:"Moderate."},
  topics:[{name:"Inverse of a Matrix & System of Equations",priority:1,note:"A⁻¹=adj(A)/|A|, used to solve AX=B — very standard numerical, frequently a full long-answer question."},
   {name:"Properties of Determinants",priority:2,note:"Row/column operations to simplify and evaluate a determinant — technique-based question."}],
  mustKnow:["Adjoint and inverse formula; consistency conditions for a linear system via |A|.","Row/column operation rules that don't change determinant value.","Symmetric/skew-symmetric matrix decomposition."],
  pyqTypes:["Solve a system of 3 linear equations using the matrix method (find A⁻¹ and X=A⁻¹B).","Prove a determinant identity using row/column operations."],
  mistakes:["Cofactor sign errors when computing the adjoint.","Arithmetic slips during row/column operations on a 3×3 determinant."],
  prereq:["Relations and Functions"], connected:["Vectors and Three-Dimensional Geometry"]},

 {name:"Calculus — Continuity, Differentiability & Applications of Derivatives", priority:1,
  importance:"Calculus overall is reported at 36/80 marks — by far the largest single unit (~45% of the theory paper); this sub-topic (continuity/differentiability/AOD) is a core, heavily-weighted, near-guaranteed source of long-answer questions.",
  pyq:{freq:"Part of Calculus's combined ~36/80 marks (Historical/PYQ-based trend — the single most consistently corroborated figure found in this research, matching across 2 independent sources).",historical:"Consistently the dominant unit in RBSE Class 12 Maths.",pattern:"Continuity/differentiability of piecewise functions, maxima-minima optimisation word problems, tangent-normal, rate of change.",difficulty:"Moderate-Hard."},
  topics:[{name:"Continuity & Differentiability of Piecewise Functions",priority:1,note:"Find unknown constants making a function continuous/differentiable at a junction — standard technique question."},
   {name:"Maxima-Minima (Applications of Derivatives)",priority:1,note:"Optimisation word problems (max area/volume/min cost) — very frequent long-answer question."},
   {name:"Tangent, Normal & Rate of Change",priority:2,note:"Equation of tangent/normal at a point; related-rates problems — standard technique question."}],
  mustKnow:["Differentiability implies continuity, not vice versa — always check continuity first.","First/second derivative test for local maxima/minima.","Standard derivative formulas including implicit and parametric differentiation."],
  pyqTypes:["Given a piecewise function, find constants for continuity/differentiability at the junction point.","Optimisation word problem — set up, differentiate, and solve for the optimum value (a very common full long-answer question)."],
  mistakes:["Checking continuity only when differentiability is explicitly required.","Forgetting to verify the second-derivative sign (or use the sign-change test correctly) to classify max vs min."],
  prereq:["Relations and Functions"], connected:["Integrals","Differential Equations"]},

 {name:"Calculus — Integrals & Applications of Integrals", priority:1,
  importance:"Part of the same dominant Calculus unit (36/80 marks combined); definite-integral techniques and area-under-curve problems are dense and consistently tested as long-answer questions.",
  pyq:{freq:"Part of Calculus's combined ~36/80 marks.",historical:"Consistently high, as part of the largest unit in the paper.",pattern:"Integration by parts/substitution, definite integral using standard properties, area bounded by curves.",difficulty:"Hard."},
  topics:[{name:"Integration Techniques (by parts, substitution, partial fractions)",priority:1,note:"ILATE rule, standard substitution patterns — calculation-heavy but formulaic question."},
   {name:"Definite Integral Properties",priority:1,note:"Use symmetry/King's-property tricks to simplify a hard-looking definite integral."},
   {name:"Area Bounded by Curves",priority:1,note:"Area between a curve and a line/two curves — very common long-answer question."}],
  mustKnow:["ILATE priority order for choosing 'u' in integration by parts.","Standard definite-integral property: ∫₀ᵃf(x)dx=∫₀ᵃf(a-x)dx.","Area = ∫(upper−lower)dx between correctly found intersection limits."],
  pyqTypes:["Evaluate a definite integral using a standard property rather than direct computation.","Find the area enclosed between a given curve and a line/another curve."],
  mistakes:["Wrong upper/lower curve order leading to negative computed area.","Missing partial-fraction decomposition step for a rational integrand."],
  prereq:["Continuity, Differentiability & AOD"], connected:["Differential Equations"]},

 {name:"Differential Equations", priority:2,
  importance:"Part of the Calculus unit's overall dominant weight; variable-separable and linear first-order DE questions are a standard, formulaic long-answer type.",
  pyq:{freq:"Part of Calculus's combined ~36/80 marks.",historical:"Stable moderate-high, as part of the largest unit.",pattern:"Formation of a differential equation, solving variable-separable/linear/homogeneous first-order DEs using integrating factor.",difficulty:"Moderate-Hard."},
  topics:[{name:"Linear First-Order DE & Integrating Factor",priority:1,note:"dy/dx+Py=Q; IF=e^∫Pdx — standard solving-technique question."},
   {name:"Homogeneous Differential Equations",priority:2,note:"Substitution y=vx — recurring technique question."}],
  mustKnow:["Order and degree definitions (after removing radicals/fractions).","Integrating factor method for linear first-order DEs.","Homogeneous DE recognition: dy/dx=f(y/x)."],
  pyqTypes:["Solve a given linear first-order DE with an initial condition to find the particular solution.","Form the differential equation for a given family of curves."],
  mistakes:["Forgetting the arbitrary constant when finding the integrating factor's exponent.","Misidentifying a DE as homogeneous when it isn't expressible as f(y/x)."],
  prereq:["Integrals"], connected:["Applications of Derivatives (rate problems)"]},

 {name:"Vectors and Three-Dimensional Geometry", priority:1,
  importance:"Reported at 16/80 marks — the second-largest unit after Calculus; shortest-distance-between-lines and plane-equation numericals are dependable, formula-driven long-answer questions with strong JEE Main overlap.",
  pyq:{freq:"~16 of 80 theory marks (Historical/PYQ-based trend, reasonably corroborated across 2 sources).",historical:"Consistently the second-largest unit in the paper.",pattern:"Shortest distance between two lines, equation of a plane, angle between line/plane, direction cosines.",difficulty:"Moderate."},
  topics:[{name:"Shortest Distance Between Two Skew Lines",priority:1,note:"Formula using direction vectors and connecting vector — very standard, recurring long-answer question."},
   {name:"Equation of a Plane",priority:1,note:"Plane through 3 points / containing a line — frequent long-answer question."},
   {name:"Dot & Cross Product Applications",priority:2,note:"Area of triangle/parallelogram, angle between vectors — direct-formula question."}],
  mustKnow:["Skew-line shortest-distance formula (determinant/box-product form).","General plane equation and angle between two planes via normal vectors.","Direction cosines vs direction ratios distinction."],
  pyqTypes:["Find the shortest distance between two given skew lines (a very frequently recurring exact question type).","Find the equation of a plane satisfying given point/line/perpendicularity conditions."],
  mistakes:["Arithmetic slips in the 3×3 determinant for shortest-distance/plane-equation formulas.","Confusing direction ratios (unnormalised) with direction cosines (normalised)."],
  prereq:["Matrices & Determinants"], connected:["Algebra (Matrices & Determinants)"]},

 {name:"Linear Programming", priority:3,
  importance:"Reported at only 4/80 marks — the smallest unit in the paper; graphical-method questions are simple and quick once the method is practiced.",
  pyq:{freq:"~4 of 80 theory marks — smallest unit (Historical/PYQ-based trend, reasonably corroborated).",historical:"Consistently the lightest-weight unit.",pattern:"Formulate and graphically solve a linear programming problem (maximise/minimise an objective function subject to constraints).",difficulty:"Easy-Moderate."},
  topics:[{name:"Graphical Method for LPP",priority:1,note:"Plot constraint inequalities, identify feasible region, evaluate objective function at corner points — standard full-question type."}],
  mustKnow:["Feasible region is the intersection of all constraint half-planes (plus non-negativity).","Optimal value of objective function occurs at a corner (vertex) point of the feasible region.","Unbounded feasible region needs care — optimum may not exist for one of max/min."],
  pyqTypes:["Given constraints and an objective function, graph the feasible region and find the optimal value."],
  mistakes:["Plotting an inequality's boundary line but shading the wrong side.","Forgetting to check all corner points, not just the visually 'extreme' one."],
  prereq:["Algebra (Matrices & Determinants), basic graphing"], connected:["Probability"]},

 {name:"Probability", priority:2,
  importance:"Reported at 7/80 marks; conditional probability and Bayes' theorem word problems are a reliable, standalone long-answer question type.",
  pyq:{freq:"~7 of 80 theory marks (Historical/PYQ-based trend, reasonably corroborated).",historical:"Stable moderate weight.",pattern:"Conditional probability, Bayes' theorem word problems, probability distribution (mean/variance of a random variable).",difficulty:"Moderate."},
  topics:[{name:"Conditional Probability & Bayes' Theorem",priority:1,note:"Multi-stage word problems (item from one of several sources found defective) — very standard long-answer question."},
   {name:"Probability Distribution",priority:2,note:"Mean and variance of a discrete random variable — direct-formula question."}],
  mustKnow:["Bayes' theorem formula and correct identification of prior/conditional probabilities in a word problem.","Independent vs mutually exclusive event conditions (not the same thing).","Mean E(X)=Σx·P(x); variance=E(X²)−[E(X)]²."],
  pyqTypes:["Multi-stage probability word problem solved using Bayes' theorem.","Given a probability distribution table, find mean and variance."],
  mistakes:["Confusing independent and mutually exclusive event definitions.","Setting up the wrong conditional probability direction (P(A|B) vs P(B|A)) in a Bayes' problem."],
  prereq:["Linear Programming (basic set-up reasoning, not strictly required)"], connected:["Relations and Functions"]},
];

// Hindi/English: structural elements (marks split, sections, grammar, writing) are reasonably corroborated;
// exact literature chapter list is genuinely disputed between sources (see caveats in build script). We
// provide a reusable per-chapter study framework instead of inventing unverified chapter content.

const HINDI_GRAMMAR = [
  ["1", "संधि (Sandhi) — स्वर, व्यंजन, विसर्ग", "🟠 P2", "भेद पहचानना व उदाहरण देना", "1-2"],
  ["2", "समास (Samas)", "🟠 P2", "समास-विग्रह व भेद पहचान", "2"],
  ["3", "उपसर्ग-प्रत्यय (Prefix-Suffix)", "🟡 P3", "शब्द-निर्माण व अर्थ-परिवर्तन", "1-2"],
  ["4", "मुहावरे व लोकोक्तियाँ (Idioms & Proverbs)", "🔴 P1", "वाक्य में प्रयोग करना", "2"],
  ["5", "अलंकार (Figures of Speech)", "🟠 P2", "पहचान व उदाहरण (अनुप्रास, यमक, उपमा)", "2"],
  ["6", "रस (Rasa)", "🟡 P3", "पहचान व स्थायी भाव सहित परिभाषा", "1-2"],
  ["7", "वाक्य शुद्धि / वाक्य-सुधार", "🟠 P2", "अशुद्ध वाक्य को शुद्ध करना", "2-3"],
  ["8", "पद-परिचय (Parts of speech analysis)", "🟡 P3", "दिए गए वाक्य में पद का व्याकरणिक परिचय", "2"],
];
const HINDI_WRITING = [
  ["निबंध लेखन (Essay)", "लगभग 300 शब्द, भूमिका-विषय-वस्तु-उपसंहार संरचना", "सामाजिक/राष्ट्रीय/समसामयिक विषय", "5-6", "स्पष्ट संरचना व उदाहरण न देना सबसे आम गलती"],
  ["पत्र लेखन (Letter)", "औपचारिक/अनौपचारिक प्रारूप, दिनांक-पता-विषय अनिवार्य", "शिकायत पत्र, आवेदन पत्र", "4-5", "प्रारूप (format) भूल जाना अंक कटवाता है"],
  ["अनुच्छेद लेखन (Paragraph)", "लगभग 80-100 शब्द, एक ही भाव पर केंद्रित", "दिए गए शीर्षक पर संक्षिप्त लेखन", "3-4", "विषय से भटक जाना"],
  ["संवाद लेखन / सारांश (Dialogue/Summary)", "दिए गए अवतरण का संक्षिप्तीकरण मूल भाव सहित", "गद्यांश/पद्यांश का सारांश", "3-4", "मूल शब्दों की नकल करना, अपने शब्दों में न लिखना"],
];

const ENGLISH_GRAMMAR = [
  ["1", "Tenses", "🔴 P1", "Transformation & error-correction based", "3-4"],
  ["2", "Voice (Active/Passive)", "🔴 P1", "Sentence transformation", "2-3"],
  ["3", "Narration (Direct/Indirect)", "🔴 P1", "Sentence transformation", "2-3"],
  ["4", "Modals & Conditionals", "🟠 P2", "Fill-in-the-blank / gap-filling", "2"],
  ["5", "Prepositions & Conjunctions", "🟠 P2", "Gap-filling in a passage", "2"],
  ["6", "Determiners & Articles", "🟡 P3", "Fill-in-the-blank", "1-2"],
  ["7", "Clauses (Noun/Adjective/Adverb)", "🟡 P3", "Identification & combination", "2"],
  ["8", "Synthesis of Sentences", "🟡 P3", "Combine sentences using given connector", "2"],
];
const ENGLISH_WRITING = [
  ["Formal/Informal Letter", "Sender-receiver address, subject, body, closing", "Application, complaint, personal letter", "5-6", "Missing format elements (address, subject line)"],
  ["Notice Writing", "Boxed format, heading 'NOTICE', issuing authority, date", "School/organisation notice", "3-4", "Forgetting the box or issuing authority signature"],
  ["Advertisement", "Boxed, catchy heading, concise essential details only", "Classified/product/situation-vacant ad", "3-4", "Overly wordy — should be telegraphic/concise"],
  ["Report Writing", "Heading, byline, place-date, factual third-person tone", "Event/incident report", "5-6", "Slipping into first-person/opinionated tone"],
  ["Paragraph/Article Writing", "Title, coherent single-topic paragraph, word limit", "Given topic based composition", "4-5", "Exceeding word limit or losing topical focus"],
];

module.exports = { PHYSICS, CHEMISTRY, MATH, HINDI_GRAMMAR, HINDI_WRITING, ENGLISH_GRAMMAR, ENGLISH_WRITING };
