// JEE Main content data. Priorities & PYQ trend labels are Historical/PYQ-based-trend
// (cross-referenced across Allen/PW/esaral/Vedantu/CollegeDekho/Career360/Motion) unless
// stated as "Official" — NTA does not publish chapter-wise marks.

const PHYSICS = [
 {name:"Units and Measurements", priority:3,
  importance:"Small chapter but historically produces a disproportionate share of quick, calculation-light questions (PW: ~33 Q across recent sessions) — excellent scoring-per-minute ratio even though it isn't conceptually deep.",
  pyq:{freq:"1 question in most shifts — occasionally 0 or 2 (Historical/PYQ-based trend).",historical:"Consistently present across almost every session for a decade.",pattern:"Dimensional analysis, error/percentage-error in a derived quantity, unit conversion in SI/CGS.",difficulty:"Easy–Moderate; time cost is low if formulas are memorised."},
  topics:[
   {name:"Dimensional Analysis",priority:1,note:"Check/derive formula validity; find dependence of a quantity on others via dimensions — direct 1-mark type."},
   {name:"Errors in Measurement",priority:2,note:"Propagation of error in products/quotients/powers — numerical with %error given, asks for %error in result."},
   {name:"Significant Figures",priority:3,note:"Rules for addition/multiplication rounding — short factual question."},
  ],
  mustKnow:["[M^aL^bT^c] form of every derived unit you use elsewhere (force, energy, pressure, viscosity).","Error propagation: for Z=A^p B^q/C^r, ΔZ/Z = pΔA/A+qΔB/B+rΔC/C.","Least count rules for vernier caliper & screw gauge."],
  pyqTypes:["Given a formula with unknown exponents, find them by dimensional homogeneity.","Numerical: percentage error in g from a simple pendulum experiment."],
  mistakes:["Forgetting error contributions add (never subtract) even when the formula has a minus sign.","Confusing significant figures in subtraction of two large near-equal numbers."],
  prereq:[], connected:["Every numerical-heavy chapter (Mechanics, Electricity)"]},

 {name:"Kinematics", priority:3,
  importance:"Foundational — every later Mechanics and Electrodynamics chapter (projectile-like motion, circular motion in fields) reuses this. Standalone weight is moderate but conceptual leverage is high.",
  pyq:{freq:"0–1 direct question; concepts reused inside Laws of Motion / Rotational Motion problems.",historical:"Stable low-to-moderate direct share for years.",pattern:"Graph-based (v-t, x-t), relative velocity, projectile range/height, circular motion basics.",difficulty:"Easy–Moderate."},
  topics:[
   {name:"Motion in a Plane / Projectile Motion",priority:1,note:"Range, max height, time of flight formulas; graph of trajectory — frequent numerical."},
   {name:"Relative Velocity",priority:2,note:"River-boat / rain-man problems — vector subtraction based numerical."},
   {name:"Uniform Circular Motion",priority:2,note:"Centripetal acceleration direction/magnitude — conceptual + numerical link to Rotational Motion & Gravitation."},
  ],
  mustKnow:["Equations of motion (v=u+at etc.) applied component-wise in 2D.","Range=u²sin2θ/g, Hmax=u²sin²θ/2g, T=2usinθ/g.","Graph slope/area interpretations (v-t area = displacement)."],
  pyqTypes:["Read a v-t or x-t graph and compute displacement/acceleration at an instant.","Two-body relative velocity/ minimum-distance-of-approach problem."],
  mistakes:["Sign errors when resolving vectors into components.","Using scalar speed formulas where a vector (relative velocity) is required."],
  prereq:["Units & Measurements","Basic vectors"], connected:["Laws of Motion","Rotational Motion","Gravitation"]},

 {name:"Laws of Motion", priority:2,
  importance:"Directly tested via friction/pulley/connected-body numericals and forms the base of every dynamics question, including in Rotational Motion and Gravitation.",
  pyq:{freq:"1 question most sessions.",historical:"Perennial — one of the oldest stable chapters in weightage.",pattern:"Connected bodies with pulleys, friction on inclined planes, momentum conservation.",difficulty:"Moderate."},
  topics:[
   {name:"Friction",priority:1,note:"Static vs kinetic friction, angle of repose — numerical with inclined plane + block."},
   {name:"Connected Bodies / Pulley Systems",priority:1,note:"Tension, common acceleration via Newton's second law on each block — multi-body numerical."},
   {name:"Conservation of Linear Momentum",priority:2,note:"Collision-adjacent problems, recoil — direct application question."},
  ],
  mustKnow:["F=ma applied per body with correct free-body diagram.","f_s(max)=μsN, f_k=μkN; angle of repose tanθ=μ.","Momentum conservation in absence of external force."],
  pyqTypes:["Two/three-block system on a frictionless or rough surface — find tension/acceleration.","Pseudo-force problems in accelerating frames (lift problems)."],
  mistakes:["Wrong direction assumed for friction (must oppose relative sliding tendency).","Forgetting normal force changes on an incline (N=mg cosθ, not mg)."],
  prereq:["Kinematics"], connected:["Work Energy Power","Rotational Motion","Gravitation"]},

 {name:"Work, Energy and Power", priority:2,
  importance:"Energy-conservation method is the fastest solving tool across Mechanics, Gravitation and even Electrostatics-analogy problems, keeping this chapter consistently relevant.",
  pyq:{freq:"1 question most sessions.",historical:"Stable moderate-high share for a decade.",pattern:"Work-energy theorem, spring PE, elastic/inelastic collisions, power in circular/inclined motion.",difficulty:"Moderate."},
  topics:[
   {name:"Work-Energy Theorem",priority:1,note:"ΔKE = Work done by all forces — used to bypass kinematics in variable-force problems."},
   {name:"Collisions (elastic & inelastic)",priority:1,note:"1D/2D collision velocity formulas, coefficient of restitution — standard numerical."},
   {name:"Spring Potential Energy",priority:2,note:"½kx² combined with gravity in vertical-spring numericals."},
  ],
  mustKnow:["KE=½mv², PE=mgh, spring PE=½kx².","Elastic collision (equal mass): velocities exchange.","Power = F·v (instantaneous), work/time (average)."],
  pyqTypes:["Block sliding down a rough incline then compressing a spring — find compression.","2D oblique elastic collision — find final velocity directions."],
  mistakes:["Applying energy conservation while ignoring friction (non-conservative) work.","Confusing coefficient of restitution definition (e = relative velocity of separation/approach)."],
  prereq:["Laws of Motion","Kinematics"], connected:["Rotational Motion","Gravitation","Oscillations"]},

 {name:"Rotational Motion (System of Particles)", priority:1,
  importance:"One of the highest and most consistently-flagged Mechanics chapters across esaral/PW/Vedantu (all three rank it top-tier) — rich in formula combinations (torque, angular momentum, moment of inertia) that examiners can mix in many ways.",
  pyq:{freq:"1–2 questions most sessions — among the highest-yield Mechanics chapters.",historical:"Consistently top-3 in Mechanics across multi-year institute analyses.",pattern:"Moment of inertia of standard bodies, rolling without slipping, angular momentum conservation.",difficulty:"Moderate–Hard."},
  topics:[
   {name:"Moment of Inertia & Parallel/Perpendicular Axis Theorems",priority:1,note:"MI of rod/disc/ring/sphere — direct formula recall + theorem application question."},
   {name:"Rolling Motion (rolling without slipping)",priority:1,note:"KE = ½mv²(1+k²/R²); race-down-incline comparisons between shapes — classic numerical."},
   {name:"Angular Momentum Conservation",priority:1,note:"Person-on-rotating-disc / collision with rod pivoted at end — numerical with L conserved."},
   {name:"Torque & Equilibrium of Rigid Bodies",priority:2,note:"Balancing beam / ladder-against-wall problems — static equilibrium condition ΣF=0, Στ=0."},
  ],
  mustKnow:["MI table for ring, disc, rod (about centre & end), solid/hollow sphere.","Rolling condition v=ωR; acceleration down incline a=gsinθ/(1+k²/R²).","L=Iω conserved when net external torque is zero."],
  pyqTypes:["Race between a ring, disc and sphere down an incline — rank arrival order/time.","Angular momentum conservation when a mass is dropped onto or leaves a rotating system."],
  mistakes:["Using linear KE formula and forgetting the rotational KE term for rolling bodies.","Applying torque equilibrium about the wrong pivot, missing a force's moment arm."],
  prereq:["Laws of Motion","Work Energy Power","Basic vectors (cross product)"], connected:["Gravitation","Magnetic Effects of Current (torque on a loop)"]},

 {name:"Gravitation", priority:3,
  importance:"Moderate, steady weightage; conceptually connects to Rotational Motion (orbital angular momentum) and Oscillations (time period variants).",
  pyq:{freq:"0–1 question most sessions.",historical:"Stable moderate share.",pattern:"Orbital velocity/time period, escape velocity, variation of g with height/depth, gravitational PE.",difficulty:"Moderate."},
  topics:[
   {name:"Orbital Velocity & Time Period (Kepler's laws)",priority:1,note:"v=√(GM/r), T²∝r³ — satellite numericals."},
   {name:"Variation of g",priority:2,note:"With height (g'=g(1-2h/R)) and depth (g'=g(1-d/R)) — direct substitution numerical."},
   {name:"Escape Velocity & Gravitational PE",priority:2,note:"PE=-GMm/r; escape velocity ve=√(2GM/R) — energy-conservation based numerical."},
  ],
  mustKnow:["Kepler's three laws (statement + T²∝r³).","g at surface = GM/R²; escape velocity independent of mass of projectile.","Binding energy of a satellite = -Total energy."],
  pyqTypes:["Two-planet/two-satellite comparison ratio problems using Kepler's third law.","Energy required to move a satellite from one orbit to another."],
  mistakes:["Sign errors with gravitational PE (always negative, taken zero at infinity).","Confusing orbital velocity formula with escape velocity formula."],
  prereq:["Laws of Motion","Circular Motion (Kinematics)"], connected:["Rotational Motion","Oscillations (pendulum variants)"]},

 {name:"Mechanical Properties of Solids & Fluids", priority:3,
  importance:"Moderate weight; Reynolds number and Newton's law of cooling are officially deleted, narrowing this chapter's scope, which slightly reduces its question variety but keeps core formulas testable.",
  pyq:{freq:"0–1 question, sometimes merged as one question covering both solids and fluids.",historical:"Stable low-moderate share.",pattern:"Young's modulus/stress-strain, Bernoulli's theorem, surface tension (excess pressure in a drop/bubble), viscosity (terminal velocity).",difficulty:"Moderate."},
  topics:[
   {name:"Stress-Strain & Young's Modulus",priority:1,note:"Elongation of a wire under load — direct numerical, sometimes with a graph."},
   {name:"Bernoulli's Theorem & Equation of Continuity",priority:1,note:"Venturimeter / efflux speed from a tank — classic numerical."},
   {name:"Surface Tension",priority:2,note:"Excess pressure in a soap bubble/drop, capillary rise — formula-substitution numerical."},
  ],
  mustKnow:["Y=stress/strain; excess pressure in drop=2T/r, in bubble=4T/r.","Bernoulli: P+½ρv²+ρgh=const; continuity A1v1=A2v2.","Terminal velocity vt ∝ r² (Stokes' law) — Reynolds number itself is deleted, but terminal velocity numericals remain."],
  pyqTypes:["Efflux velocity from a hole in a tank at given depth, range on ground.","Two liquid drops merging — find new radius/excess pressure/energy released."],
  mistakes:["Using density of liquid instead of density of solid (or vice versa) in Stokes' law problems.","Forgetting bubble has two surfaces (factor of 4T/r, not 2T/r)."],
  prereq:["Units & Measurements"], connected:["Kinetic Theory of Gases","Oscillations"]},

 {name:"Thermodynamics", priority:2,
  importance:"Flagged high-frequency by multiple institute analyses (esaral, PW top-5); shares strong overlap with Chemistry's Thermodynamics, so concepts double as JEE Chemistry prep too. Carnot engine efficiency is officially deleted.",
  pyq:{freq:"1 question most sessions.",historical:"Consistently top-5 in Physics per PW.",pattern:"First law numericals (isothermal/adiabatic/isochoric processes), P-V diagrams, efficiency of a cycle (non-Carnot cycles still testable).",difficulty:"Moderate."},
  topics:[
   {name:"First Law of Thermodynamics & Processes",priority:1,note:"ΔQ=ΔU+ΔW for isothermal/adiabatic/isobaric/isochoric — direct substitution numerical."},
   {name:"P-V Diagrams & Work Done",priority:1,note:"Work = area under P-V curve; cyclic process net work — graph-reading question."},
   {name:"Efficiency of a Heat Engine / Cyclic Process",priority:2,note:"η=1-Q2/Q1 for a given cycle (not the deleted Carnot-specific derivation) — numerical."},
  ],
  mustKnow:["ΔU depends only on temperature for an ideal gas (path-independent).","Adiabatic: PVᵞ=const, W=(P1V1-P2V2)/(γ-1).","Cyclic process: ΔU=0 over one cycle, so Q=W."],
  pyqTypes:["Given a P-V diagram (rectangle/triangle/cycle), find net work and heat exchanged per leg.","Mixed process numerical: gas taken isothermal then adiabatic — find final state variables."],
  mistakes:["Sign convention mix-ups (work done BY gas vs ON gas).","Treating adiabatic and isothermal formulas interchangeably."],
  prereq:["Kinetic Theory of Gases (basic)"], connected:["Kinetic Theory of Gases","Chemistry: Chemical Thermodynamics"]},

 {name:"Kinetic Theory of Gases", priority:3,
  importance:"Moderate weight; often tested jointly with Thermodynamics in a single question, and rms-speed/degrees-of-freedom concepts are reused in Thermodynamics numericals.",
  pyq:{freq:"0–1 question.",historical:"Stable moderate share.",pattern:"rms/average speed of gas molecules, degrees of freedom & specific heats (Cp, Cv, γ), ideal gas equation numericals.",difficulty:"Easy–Moderate."},
  topics:[
   {name:"rms Speed & Kinetic Energy of Gas",priority:1,note:"vrms=√(3RT/M); KE per mole = (3/2)RT — direct-substitution numerical."},
   {name:"Degrees of Freedom & Specific Heats",priority:1,note:"Cv=(f/2)R, Cp=Cv+R, γ=Cp/Cv for mono/di/polyatomic gases — factual + numerical."},
   {name:"Ideal Gas Equation & Mixtures of Gases",priority:2,note:"PV=nRT; mixture of two gases — find equivalent γ or molar mass."},
  ],
  mustKnow:["vrms:vavg:vmp ratio = √3:√(8/π):√2 (approx values).","γ=5/3 (mono), 7/5 (dia), 4/3 (poly, with vibration 9/7 in some cases).","PV=nRT and its use to find density/molar mass."],
  pyqTypes:["Mixture of two ideal gases — find resultant Cp/Cv or γ.","Given temperature change, find rms speed ratio before/after."],
  mistakes:["Using Celsius instead of Kelvin in any gas-law formula.","Wrong degrees-of-freedom count for diatomic gas at high vs normal temperature."],
  prereq:["Thermodynamics (basic)"], connected:["Thermodynamics","Oscillations & Waves"]},

 {name:"Oscillations and Waves", priority:4,
  importance:"Flagged as one of the lowest-weightage Physics chapters (Vedantu: ~1.94%); free/forced/damped oscillations, resonance and Doppler effect in sound are officially deleted, shrinking the testable scope further to core SHM.",
  pyq:{freq:"0–1 question, often skipped entirely in a given shift.",historical:"Historically low compared to Electrodynamics/Mechanics.",pattern:"SHM equations (displacement/velocity/acceleration), simple pendulum time period, spring-mass system, basic wave equation/superposition.",difficulty:"Easy–Moderate."},
  topics:[
   {name:"Simple Harmonic Motion (SHM) basics",priority:1,note:"x=A sin(ωt+φ); v and a formulas; energy in SHM — direct-substitution numerical."},
   {name:"Simple Pendulum & Spring-Mass System",priority:2,note:"T=2π√(l/g) and T=2π√(m/k) — comparison/ratio numericals."},
   {name:"Wave Equation & Superposition",priority:3,note:"y=A sin(kx-ωt); standing waves in strings/pipes — factual + short numerical."},
  ],
  mustKnow:["Total energy in SHM = ½mω²A² (constant); KE and PE interconvert.","Standard pendulum/spring time-period formulas and how T changes if l, g, m, or k change.","Standing wave node/antinode spacing = λ/2, λ/4."],
  pyqTypes:["Given SHM equation, find velocity/acceleration at a specific displacement or time.","Spring-mass or pendulum taken to another planet/lift — find new time period."],
  mistakes:["Confusing angular frequency ω with frequency f (ω=2πf).","Applying pendulum formula for large angular amplitude where SHM approximation fails."],
  prereq:["Circular Motion","Laws of Motion"], connected:["Sound-related Physics generally (Waves is now a light-weight topic)"]},

 {name:"Electrostatics", priority:1,
  importance:"Top-tier chapter across sources (PW: 27 Q, Vedantu: 4.49%); forms the conceptual base for Current Electricity and Capacitance, both also high-priority — mastering this chapter has compounding returns.",
  pyq:{freq:"1–2 questions most sessions.",historical:"Consistently one of the top 3 Electrodynamics chapters.",pattern:"Electric field/potential due to charge configurations, Gauss's law, capacitor combinations, energy stored.",difficulty:"Moderate–Hard."},
  topics:[
   {name:"Electric Field & Potential due to Point/Continuous Charges",priority:1,note:"Field of ring/disc/rod on axis; potential due to dipole — standard derivation-based numerical."},
   {name:"Gauss's Law Applications",priority:1,note:"Field due to infinite sheet/cylinder/sphere (conducting & non-conducting) — symmetry-based numerical."},
   {name:"Capacitors (series/parallel, energy, dielectric)",priority:1,note:"Equivalent capacitance after inserting a dielectric slab or changing plate separation — very frequent numerical style."},
  ],
  mustKnow:["E and V formulas for point charge, dipole (axial & equatorial), charged sphere (inside/outside).","Gauss's law: flux = Qenclosed/ε₀ — pick the right symmetric surface.","Energy stored U=½CV²=½QV=Q²/2C; effect of dielectric on C, Q, V, E, U depending on battery connected/disconnected."],
  pyqTypes:["Capacitor network reduction with a dielectric inserted partially — find new capacitance/energy.","Field/potential at a point due to a combination of point charges or a charged ring/disc."],
  mistakes:["Forgetting to check whether battery stays connected (V constant) or is disconnected (Q constant) before/after a dielectric change.","Sign errors in potential due to multiple charges (potential is scalar — add algebraically, not vectorially)."],
  prereq:["Basic vectors","Units & Measurements"], connected:["Current Electricity","Electromagnetic Induction","Chemistry: Chemical Bonding (dipole concepts)"]},

 {name:"Current Electricity", priority:1,
  importance:"Reported as the single highest-weightage Physics chapter by multiple sources (esaral: ~9.9%, Vedantu: 6.57% 'highest in physics') — an unmissable, extremely high-ROI chapter.",
  pyq:{freq:"2 questions in most sessions — the most reliably-tested Physics chapter.",historical:"#1 or #2 ranked chapter across nearly every institute analysis for years.",pattern:"Equivalent resistance after reconfiguring a circuit (Wheatstone bridge/grid), Kirchhoff's laws, cell combinations with internal resistance.",difficulty:"Moderate–Hard."},
  topics:[
   {name:"Equivalent Resistance in Complex Networks",priority:1,note:"Wheatstone bridge balance condition, symmetry-based reduction, folding/unfolding grid circuits — extremely common numerical style."},
   {name:"Kirchhoff's Laws & Circuit Analysis",priority:1,note:"Multi-loop circuits with multiple EMF sources — junction/loop equations numerical."},
   {name:"Cells: Grouping & Internal Resistance",priority:2,note:"Series/parallel cell combination for max current/power in external resistance — numerical + conceptual."},
  ],
  mustKnow:["Balanced Wheatstone bridge: no current through galvanometer when P/Q=R/S.","Kirchhoff's current law (junction) and voltage law (loop) sign conventions.","Power dissipation P=I²R=V²/R=VI; max power transfer when external R=internal r."],
  pyqTypes:["'Equivalent resistance after changing the circuit configuration' — classic recurring phrasing across years.","Meter-bridge/potentiometer style numerical asking for unknown resistance or balancing length (note: potentiometer topic itself is officially trimmed — expect lighter treatment)."],
  mistakes:["Wrong sign convention while traversing a loop (direction of assumed current vs EMF polarity).","Missing a symmetry shortcut and solving a large grid the long way, wasting time."],
  prereq:["Electrostatics (potential difference concept)"], connected:["Magnetic Effects of Current","Electromagnetic Induction","Semiconductor Electronics"]},

 {name:"Magnetic Effects of Current & Magnetism", priority:2,
  importance:"'Magnetic Effects' portion is high-frequency (esaral 6.6%), but the 'Magnetism & Matter' portion (Earth's magnetism, hysteresis, susceptibility — largely trimmed) is now one of the lowest-weightage areas (Vedantu ~1.90%) — treat the two halves very differently in prep priority.",
  pyq:{freq:"1 question most sessions, almost always from the Magnetic-Effects half rather than Magnetism & Matter.",historical:"Magnetic Effects stable-high; Magnetism & Matter stable-low (and further trimmed by the 2023-24 rationalization).",pattern:"Force on a current-carrying wire/loop in a field, torque on a dipole/loop, field due to a straight wire/loop/solenoid (Biot-Savart/Ampere's law).",difficulty:"Moderate."},
  topics:[
   {name:"Biot-Savart Law & Ampere's Law",priority:1,note:"Field due to a straight wire, circular loop (centre/axis), solenoid — direct formula numerical."},
   {name:"Force & Torque on a Current Loop in a Magnetic Field",priority:1,note:"F=IL×B; τ=m×B for a magnetic dipole — moving-coil-galvanometer-style numerical."},
   {name:"Motion of a Charge in Combined E & B Fields",priority:2,note:"Circular/helical path radius r=mv/qB; velocity selector — numerical linking to Electrostatics."},
  ],
  mustKnow:["Biot-Savart field formulas for straight wire (finite/infinite), loop centre, solenoid (B=μ₀nI).","Force between two parallel current-carrying wires (attractive if same direction).","Cyclotron radius/frequency formulas (cyclotron itself is a deleted sub-topic — but the radius formula still appears via charge-in-field numericals)."],
  pyqTypes:["Charged particle entering a magnetic field region — find radius of path / point of exit.","Two long parallel wires — find net field or force at a point."],
  mistakes:["Wrong right-hand-rule direction for field or force.","Forgetting current direction convention (conventional current, not electron flow) when applying F=IL×B."],
  prereq:["Electrostatics","Current Electricity","Vectors (cross product)"], connected:["Electromagnetic Induction & AC","Rotational Motion (torque)"]},

 {name:"Electromagnetic Induction & Alternating Current", priority:2,
  importance:"Flagged high by esaral (6.6%) and PW (9 marks in board-adjacent analyses); AC circuits (LCR, resonance, power factor) are a reliable, formula-driven scoring area once mastered.",
  pyq:{freq:"1 question most sessions.",historical:"Stable-high across years; quality factor topic officially deleted, slightly narrowing AC scope.",pattern:"EMF induced in a moving rod/changing area loop, self/mutual inductance, LCR series circuit impedance/resonance/power factor.",difficulty:"Moderate–Hard."},
  topics:[
   {name:"Faraday's & Lenz's Law Applications",priority:1,note:"Rod sliding on rails, loop entering/leaving a field region — EMF and induced current direction numerical."},
   {name:"Self & Mutual Inductance",priority:1,note:"L of a solenoid, energy stored ½LI², transformer-style mutual inductance — direct numerical."},
   {name:"LCR Series Circuit & Resonance",priority:1,note:"Impedance Z, resonant frequency ω₀=1/√LC, power factor cosφ — standard AC numerical."},
  ],
  mustKnow:["EMF = -dΦ/dt (Lenz's law gives direction opposing the change).","Impedance triangle for LCR series; at resonance Z=R (minimum), current maximum.","Transformer equation Vs/Vp=Ns/Np=Ip/Is (ideal, no loss)."],
  pyqTypes:["Rod/loop moving in or out of a magnetic-field region — plot or compute induced EMF/current vs time.","LCR circuit given L, C, R, and source frequency — find impedance, current, power factor, or resonant condition."],
  mistakes:["Sign confusion applying Lenz's law (induced current opposes the CHANGE in flux, not the field itself).","Forgetting that at resonance, voltage across L and C individually can exceed source voltage even though net impedance is minimum."],
  prereq:["Magnetic Effects of Current","Current Electricity","Oscillations (phasor idea)"], connected:["Electromagnetic Waves","Semiconductor Electronics"]},

 {name:"Electromagnetic Waves", priority:4,
  importance:"Small, mostly factual chapter (properties of the EM spectrum, Maxwell's displacement current idea) with low direct weight — good for a quick 1-mark question if revised, not worth deep numerical practice time.",
  pyq:{freq:"0–1 question, largely factual/definitional when it appears.",historical:"Consistently one of the smallest-weight chapters.",pattern:"Order/properties of EM spectrum, relation between E₀/B₀ and c, displacement current concept.",difficulty:"Easy."},
  topics:[
   {name:"EM Spectrum & Properties",priority:1,note:"Order of wavelength/frequency/energy of radio→gamma; applications of each band — factual recall question."},
   {name:"Displacement Current & Maxwell's Equations (conceptual)",priority:2,note:"Why Ampere's law needed correction; c=1/√(μ₀ε₀) — factual + light numerical."},
  ],
  mustKnow:["E₀=cB₀ for an EM wave; energy density formulas.","Correct increasing-wavelength order: gamma < X-ray < UV < visible < IR < microwave < radio.","EM waves are transverse; carry momentum and energy (Poynting vector idea, conceptual only)."],
  pyqTypes:["Identify/order EM spectrum bands by a given property (penetration, use in radar, etc.).","Given E₀ or B₀ of a wave, find the other using c."],
  mistakes:["Mixing up frequency vs wavelength ordering of the spectrum.","Treating EM waves as needing a medium to propagate (they don't)."],
  prereq:["Electromagnetic Induction (conceptual)"], connected:["Optics (light as an EM wave)"]},

 {name:"Ray Optics and Wave Optics", priority:1,
  importance:"One of the single highest-weightage Physics chapters across every source consulted (PW: 42 Q cumulative — top chapter; Vedantu, esaral both rank it top-tier); combines two officially separate NCERT chapters into one high-yield unit.",
  pyq:{freq:"1–2 questions most sessions, sometimes one from Ray and one from Wave optics.",historical:"Consistently #1 or top-3 across nearly all multi-year analyses.",pattern:"Lens/mirror formula with sign convention, combination of lenses, YDSE fringe width, diffraction/polarisation basics.",difficulty:"Moderate."},
  topics:[
   {name:"Lens & Mirror Formula with Sign Convention",priority:1,note:"Image formation, magnification, combination of two lenses in contact/apart — very frequent numerical."},
   {name:"Young's Double Slit Experiment (YDSE)",priority:1,note:"Fringe width β=λD/d; effect of inserting a slab or changing medium — recurring numerical style."},
   {name:"Refraction through Prism & Total Internal Reflection",priority:2,note:"Angle of deviation, critical angle, dispersion — direct-formula numerical."},
   {name:"Diffraction & Polarisation (basic)",priority:3,note:"Single-slit diffraction minima condition; Malus's law I=I₀cos²θ — factual + light numerical."},
  ],
  mustKnow:["Mirror/lens formula 1/v-1/u=1/f (Cartesian sign convention) and lensmaker's equation.","YDSE: bright fringe at path difference nλ, dark at (n+½)λ; effect of a thin film/slab shifts the pattern.","Resolving power of microscope/telescope is officially deleted — focus revision on lens combinations and YDSE instead."],
  pyqTypes:["'Numerical involving fringe width change when a transparent slab is introduced in one slit's path' — a recurring pattern.","Combination of lenses (converging+diverging) — find final image position/nature via successive application."],
  mistakes:["Sign convention errors (measuring distances against the wrong direction).","Forgetting that in YDSE, inserting a slab shifts the entire fringe pattern rather than changing fringe width."],
  prereq:["Basic Kinematics (for wave motion analogy)"], connected:["Electromagnetic Waves","Dual Nature of Radiation & Matter"]},

 {name:"Dual Nature of Radiation and Matter", priority:2,
  importance:"Core 'Modern Physics' chapter, consistently flagged mid-to-high (esaral groups Modern Physics at 6.6%); photoelectric effect numericals are formulaic and high-scoring once the equation is internalised.",
  pyq:{freq:"1 question most sessions.",historical:"Stable-high as part of the broader Modern Physics bucket (~17% of Physics per PW sub-split).",pattern:"Photoelectric equation numericals, de Broglie wavelength, stopping potential graphs.",difficulty:"Easy–Moderate."},
  topics:[
   {name:"Photoelectric Effect & Einstein's Equation",priority:1,note:"KEmax=hν-φ₀; stopping potential vs frequency graph slope = h/e — very standard numerical."},
   {name:"de Broglie Wavelength",priority:1,note:"λ=h/p for electrons/particles, often combined with accelerating-voltage numericals — frequent."},
  ],
  mustKnow:["Work function φ₀ = hν₀ (threshold frequency); photoelectric current depends on intensity, KEmax depends only on frequency.","de Broglie wavelength for an electron accelerated through V: λ=h/√(2meV).","Davisson-Germer experiment is officially deleted — skip deep derivation, know de Broglie application only."],
  pyqTypes:["Given stopping potential vs frequency data/graph, find Planck's constant or work function.","Compare de Broglie wavelengths of two particles under given conditions (mass/velocity/charge ratio)."],
  mistakes:["Confusing KEmax formula direction (depends on frequency, not intensity).","Unit errors converting eV to joules in stopping-potential numericals."],
  prereq:["Ray Optics (wave-particle duality context)","Basic Atomic Structure"], connected:["Atoms and Nuclei"]},

 {name:"Atoms and Nuclei", priority:2,
  importance:"Second half of the 'Modern Physics' bucket; radioactivity decay-law numericals and Bohr-model energy-level questions are frequent, formulaic, and fast to solve once practiced.",
  pyq:{freq:"1 question most sessions.",historical:"Stable-high; isotopes/isobars/isotones and some decay-law detail trimmed in 2023-24 rationalization.",pattern:"Bohr model energy/radius/wavelength formulas, radioactive decay (half-life, activity), nuclear binding energy/mass defect.",difficulty:"Moderate."},
  topics:[
   {name:"Bohr Model of Hydrogen Atom",priority:1,note:"En=-13.6/n² eV, rn∝n², transition wavelength via Rydberg formula — very standard numerical."},
   {name:"Radioactive Decay (half-life, mean life, activity)",priority:1,note:"N=N₀e^(-λt), A=λN — decay-law numerical, sometimes with a decay-series twist."},
   {name:"Nuclear Binding Energy & Mass Defect",priority:2,note:"BE=Δmc²; binding energy per nucleon curve interpretation (fission/fusion reasoning) — conceptual + numerical."},
  ],
  mustKnow:["Rydberg formula 1/λ=RZ²(1/n1²-1/n2²) for spectral lines.","Relation between half-life T½ and decay constant λ: T½=ln2/λ.","Binding energy per nucleon peaks around mass number ~56 (Iron) — governs fission vs fusion favourability."],
  pyqTypes:["Given initial activity/amount, find remaining quantity after n half-lives or a specific time.","Electron transition between Bohr orbits — find energy/wavelength of emitted photon."],
  mistakes:["Using n (principal quantum number) inconsistently between energy and radius formulas.","Confusing half-life with mean life in decay numericals."],
  prereq:["Dual Nature of Radiation and Matter"], connected:["Semiconductor Electronics"]},

 {name:"Semiconductor Electronics", priority:2,
  importance:"Flagged notably high by Vedantu (4.75%); the officially trimmed portions (transistor as amplifier/oscillator, detailed characteristics) reduce depth needed, but p-n junction diode application questions (rectifier, zener as voltage regulator) remain frequent.",
  pyq:{freq:"1 question most sessions.",historical:"Stable-moderate-to-high; content narrowed by 2023-24 rationalization (deep transistor theory removed).",pattern:"p-n junction diode I-V characteristics, half/full-wave rectifier working, zener diode as a voltage regulator, logic gates.",difficulty:"Easy–Moderate."},
  topics:[
   {name:"p-n Junction Diode & Rectification",priority:1,note:"Forward/reverse bias behaviour, half-wave vs full-wave rectifier circuit & output waveform — frequent conceptual+numerical."},
   {name:"Zener Diode as Voltage Regulator",priority:2,note:"Breakdown voltage usage to stabilise output voltage — conceptual application question."},
   {name:"Logic Gates (basic)",priority:2,note:"Truth tables for AND/OR/NOT/NAND/NOR, combination gate output — direct factual question."},
  ],
  mustKnow:["Diode conducts in forward bias (low resistance) and blocks in reverse bias (till breakdown).","Full-wave rectifier uses both half-cycles (via centre-tap or bridge) — smoother output than half-wave.","Basic logic gate truth tables and how to combine two gates to realise a third."],
  pyqTypes:["Identify rectifier type/output waveform from a given circuit diagram.","Given a combination of logic gates, determine the output for specific inputs."],
  mistakes:["Reversing forward/reverse bias direction convention for a diode in a circuit diagram.","Misremembering NAND/NOR truth tables under negation."],
  prereq:["Current Electricity","Atoms and Nuclei (band structure, conceptual)"], connected:["Current Electricity","Practical circuit-identification questions"]},
];

const CHEM_PHYSICAL = [
 {name:"Some Basic Concepts in Chemistry", priority:3,
  importance:"Foundational mole-concept chapter; direct weightage is modest but every stoichiometry-based numerical elsewhere depends on it. Measurement/significant-figures sub-topics are officially trimmed.",
  pyq:{freq:"0–1 direct question; concept reused everywhere else.",historical:"Stable low-direct, high-indirect importance.",pattern:"Mole concept, limiting reagent, empirical/molecular formula, molarity/molality numericals.",difficulty:"Easy–Moderate."},
  topics:[{name:"Mole Concept & Stoichiometry",priority:1,note:"Limiting reagent + % yield combined numerical — very standard style."},
   {name:"Concentration Terms",priority:2,note:"Molarity, molality, mole fraction interconversion — direct-substitution numerical."}],
  mustKnow:["Limiting reagent identification before computing product amount.","Molarity=moles/L(solution); molality=moles/kg(solvent) — never confuse the denominators.","Empirical formula from % composition → molecular formula using molar mass."],
  pyqTypes:["Reaction with a limiting reagent given masses of both reactants — find product mass/% yield.","Dilution or mixing of two solutions of different molarity — find resultant concentration."],
  mistakes:["Using volume of solution instead of mass of solvent for molality.","Forgetting to convert all quantities to moles before applying stoichiometric ratios."],
  prereq:[], connected:["Solutions","Equilibrium","Electrochemistry"]},

 {name:"Atomic Structure", priority:2,
  importance:"Flagged high-frequency by esaral (6.6%); Thomson's/Rutherford's model limitations are officially trimmed, so focus shifts to quantum numbers and electronic configuration.",
  pyq:{freq:"1 question most sessions.",historical:"Stable-high across years.",pattern:"Quantum numbers validity, electronic configuration (including exceptions like Cr, Cu), photoelectric/Bohr-model overlap with Physics.",difficulty:"Easy–Moderate."},
  topics:[{name:"Quantum Numbers & Orbital Shapes",priority:1,note:"Valid/invalid (n,l,m,s) sets; shape and orientation of s/p/d orbitals — factual + reasoning question."},
   {name:"Electronic Configuration (Aufbau, Hund's, Pauli)",priority:1,note:"Exceptions (Cr: [Ar]3d⁵4s¹, Cu: [Ar]3d¹⁰4s¹) — very commonly tested exception-based question."}],
  mustKnow:["Aufbau order via (n+l) rule; Hund's rule of maximum multiplicity; Pauli exclusion.","Exceptional configurations: Cr, Cu, Mo, Ag, Au follow extra-stability half/fully-filled d-subshell pattern.","Number of orbitals per subshell (s=1,p=3,d=5,f=7) and max electrons (2,6,10,14)."],
  pyqTypes:["Identify the exceptional electronic configuration among a list of transition elements.","Given a set of quantum numbers, decide validity/identify the orbital."],
  mistakes:["Forgetting exception cases (Cr, Cu) when writing configurations of transition metals.","Mixing up n,l,m,s definitions (e.g., assigning l values outside 0 to n-1 range)."],
  prereq:["Basic Physics: Dual Nature/Bohr Model"], connected:["Periodicity","Chemical Bonding","Coordination Compounds"]},

 {name:"Chemical Bonding and Molecular Structure", priority:1,
  importance:"High-frequency (esaral 6.6%) and conceptually central — VSEPR shapes, hybridisation and molecular orbital theory questions recur constantly and connect directly into Coordination Compounds and Organic reaction mechanisms.",
  pyq:{freq:"1 question most sessions, sometimes 2.",historical:"Consistently high across years.",pattern:"VSEPR shape prediction, hybridisation, bond angle/bond order comparison, MOT for diatomic molecules.",difficulty:"Moderate."},
  topics:[{name:"VSEPR Theory & Molecular Shapes",priority:1,note:"Predict shape from steric number + lone pairs (e.g., SF₄ seesaw, ClF₃ T-shaped) — very frequent."},
   {name:"Hybridisation",priority:1,note:"sp/sp²/sp³/sp³d/sp³d² identification from a given structure — direct question."},
   {name:"Molecular Orbital Theory (bond order, magnetic nature)",priority:2,note:"Bond order of O₂, N₂, and their ions; paramagnetic vs diamagnetic — recurring comparison question."}],
  mustKnow:["Steric number = σ-bonds + lone pairs → shape (linear, trigonal planar, tetrahedral, trigonal bipyramidal, octahedral, and distorted variants).","Bond order = ½(bonding − antibonding electrons); bond order ∝ bond strength ∝ 1/bond length.","O₂ is paramagnetic (predicted correctly only by MOT, not VBT) — a favourite conceptual trap."],
  pyqTypes:["Given a molecule/ion, predict shape and hybridisation together.","Compare bond order/magnetic behaviour of a species and its ion (e.g., O₂ vs O₂⁺ vs O₂⁻)."],
  mistakes:["Ignoring lone pairs while counting steric number, giving the wrong shape.","Applying VBT logic (which fails for O₂'s paramagnetism) instead of MOT where required."],
  prereq:["Atomic Structure"], connected:["Coordination Compounds","p-Block Elements","Organic Chemistry: GOC (bond polarity, resonance)"]},

 {name:"Chemical Thermodynamics", priority:1,
  importance:"High-frequency (PW: 30 Q); heavily numerical and formula-driven, and shares first-law concepts with Physics Thermodynamics — strong dual-benefit chapter.",
  pyq:{freq:"1 question most sessions.",historical:"Consistently high, top-5 in Physical Chemistry.",pattern:"ΔH/ΔU relation, Hess's law, entropy change, Gibbs free energy & spontaneity, bond enthalpy calculations.",difficulty:"Moderate."},
  topics:[{name:"Hess's Law & Enthalpy Calculations",priority:1,note:"Enthalpy of reaction from bond enthalpies or a cycle of given reactions — very standard numerical."},
   {name:"Gibbs Free Energy & Spontaneity",priority:1,note:"ΔG=ΔH-TΔS; sign analysis for spontaneity at various temperatures — conceptual + numerical."},
   {name:"Entropy Change in Processes",priority:2,note:"ΔS for phase change, mixing, ideal gas expansion — direct-formula numerical."}],
  mustKnow:["ΔH=ΔU+ΔnRT (relation between enthalpy and internal energy change for gaseous reactions).","ΔG<0 spontaneous, ΔG>0 non-spontaneous, ΔG=0 equilibrium — combine with ΔH,ΔS sign table.","Hess's law: total enthalpy change is path-independent — add/reverse/scale given reactions to reach the target."],
  pyqTypes:["Combine 2–3 given thermochemical equations (Hess's law) to find an unknown ΔH.","Given ΔH and ΔS, find the temperature above/below which a reaction becomes spontaneous."],
  mistakes:["Forgetting to reverse the sign of ΔH when reversing a reaction in Hess's law.","Sign errors in ΔG=ΔH-TΔS, especially with negative ΔS."],
  prereq:["Some Basic Concepts","Physics: Thermodynamics (first law)"], connected:["Equilibrium","Electrochemistry"]},

 {name:"Solutions", priority:2,
  importance:"Flagged moderately-high (Vedantu 4.54%); colligative-property numericals are formula-heavy and predictable, making this a reliable scoring chapter.",
  pyq:{freq:"1 question most sessions.",historical:"Stable-moderate-to-high.",pattern:"Raoult's law, elevation in boiling point/depression in freezing point, van't Hoff factor for electrolytes, osmotic pressure.",difficulty:"Moderate."},
  topics:[{name:"Colligative Properties",priority:1,note:"ΔTb=iKbm, ΔTf=iKfm, osmotic pressure π=iCRT — direct-substitution numerical, frequently with dissociating/associating solutes."},
   {name:"Raoult's Law & Vapour Pressure of Solutions",priority:1,note:"Ideal vs non-ideal solutions, positive/negative deviation — conceptual + numerical."},
   {name:"van't Hoff Factor",priority:2,note:"Degree of dissociation/association from measured colligative property vs theoretical value — numerical."}],
  mustKnow:["van't Hoff factor i>1 for dissociation, i<1 for association (e.g., dimerisation of acetic acid in benzene).","Raoult's law: p=p°x; deviation direction linked to solute-solvent interaction strength.","Osmotic pressure is the most sensitive colligative property (used for large/biological molecules)."],
  pyqTypes:["Given depression in freezing point for an electrolyte, find van't Hoff factor and % dissociation.","Two solutions mixed — find resultant osmotic pressure or vapour pressure."],
  mistakes:["Forgetting van't Hoff factor correction for electrolytes/associating solutes.","Using mole fraction of solute instead of solvent in Raoult's law formula."],
  prereq:["Some Basic Concepts (concentration terms)"], connected:["Chemical Thermodynamics","Electrochemistry"]},

 {name:"Equilibrium (Chemical + Ionic)", priority:1,
  importance:"High-frequency (esaral 6.6%, PW 27 Q); ionic equilibrium (pH, buffers, Ksp) is one of the most reliably-tested numerical areas in all of JEE Chemistry.",
  pyq:{freq:"1–2 questions most sessions.",historical:"Consistently top-tier in Physical Chemistry.",pattern:"Kc/Kp relation & calculation, pH of strong/weak acid-base/buffer/salt-hydrolysis, solubility product Ksp and common-ion effect.",difficulty:"Moderate–Hard."},
  topics:[{name:"Ionic Equilibrium: pH & Buffers",priority:1,note:"Henderson-Hasselbalch equation for buffer pH; pH of weak acid/base — extremely frequent numerical."},
   {name:"Solubility Product (Ksp) & Common Ion Effect",priority:1,note:"Precipitation condition (Qsp vs Ksp), solubility change on adding a common ion — standard numerical."},
   {name:"Chemical Equilibrium (Kc, Kp, Le Chatelier)",priority:2,note:"ICE-table based equilibrium concentration numericals; effect of pressure/temperature/catalyst on equilibrium position."}],
  mustKnow:["Henderson-Hasselbalch: pH=pKa+log([salt]/[acid]).","Kp=Kc(RT)^Δn — relation for gaseous equilibria.","Common-ion effect reduces solubility; compare Qsp with Ksp to predict precipitation."],
  pyqTypes:["Buffer solution pH after adding a small amount of strong acid/base.","Solubility of a sparingly soluble salt in presence of a common ion — find new solubility."],
  mistakes:["Using concentration directly instead of activity/ICE-table changes at equilibrium.","Sign/exponent errors in Δn while converting Kc to Kp."],
  prereq:["Some Basic Concepts","Chemical Thermodynamics (Gibbs energy link, conceptual)"], connected:["Redox Reactions & Electrochemistry","Coordination Compounds (Ksp overlap)"]},

 {name:"Redox Reactions and Electrochemistry", priority:2,
  importance:"Electrochemistry alone is flagged consistently high (galvanic cell/Nernst equation numericals are a JEE staple); Redox Reactions as a fully standalone question is comparatively rare (often merged into electrochemistry questions).",
  pyq:{freq:"1 question most sessions, from Electrochemistry more often than standalone Redox.",historical:"Electrochemistry stable-high; Redox alone historically low as a separate question.",pattern:"Nernst equation for cell EMF, standard electrode potential ranking, electrolysis (Faraday's laws), conductance/molar conductivity.",difficulty:"Moderate."},
  topics:[{name:"Nernst Equation & Cell EMF",priority:1,note:"EMF of a concentration cell / cell under non-standard conditions — very standard numerical."},
   {name:"Electrolysis & Faraday's Laws",priority:1,note:"Mass deposited, moles of electrons via Q=It — direct-substitution numerical."},
   {name:"Conductance & Kohlrausch's Law",priority:2,note:"Molar conductivity at infinite dilution from limiting ionic conductances — numerical."}],
  mustKnow:["Nernst equation: E=E°-(0.0591/n)logQ (at 298K).","Faraday's first law: mass deposited = ZIt = (M/nF)It.","Higher standard reduction potential = stronger oxidising agent (used to predict feasibility of a redox reaction, ΔG°=-nFE°cell)."],
  pyqTypes:["Given two half-cell potentials, find cell EMF and predict spontaneity/ΔG°.","Electrolysis numerical: given current and time, find mass/volume of product liberated."],
  mistakes:["Sign errors in Nernst equation / forgetting to write the correct cell reaction direction.","Confusing molar conductivity trend for strong vs weak electrolytes with concentration."],
  prereq:["Equilibrium (Kc/Ksp link)","Some Basic Concepts"], connected:["Equilibrium","Chemical Kinetics"]},

 {name:"Chemical Kinetics", priority:3,
  importance:"Moderate, steady weightage; rate law and half-life numericals for zero/first-order reactions are formula-driven and time-efficient once practiced.",
  pyq:{freq:"0–1 question most sessions.",historical:"Stable-moderate.",pattern:"Order of reaction from rate data, integrated rate law numericals (especially first-order half-life), Arrhenius equation (activation energy from two temperatures).",difficulty:"Moderate."},
  topics:[{name:"Integrated Rate Laws & Half-life",priority:1,note:"First-order: t½=0.693/k, k=(2.303/t)log(a/a-x) — very standard numerical."},
   {name:"Arrhenius Equation",priority:2,note:"k=Ae^(-Ea/RT); find Ea from rate constants at two temperatures — log-based numerical."},
   {name:"Order of Reaction from Experimental Data",priority:2,note:"Determine order using initial-rate method from a data table — reasoning + calculation question."}],
  mustKnow:["First-order half-life is independent of initial concentration (unique identifying feature).","Arrhenius: ln(k2/k1)=-(Ea/R)(1/T2-1/T1).","Order is experimentally determined — not from stoichiometric coefficients (unless elementary reaction stated)."],
  pyqTypes:["Given concentration vs time data, determine order and rate constant.","Two-temperature rate constant data — find activation energy or predict k at a third temperature."],
  mistakes:["Assuming reaction order equals stoichiometric coefficients without checking it's elementary.","Log/ln base confusion in first-order and Arrhenius formulas (2.303 conversion factor)."],
  prereq:["Some Basic Concepts","Equilibrium (rate-equilibrium link, conceptual)"], connected:["Equilibrium"]},
];

const CHEM_INORGANIC = [
 {name:"Classification of Elements & Periodicity", priority:2,
  importance:"Foundational for all of Inorganic Chemistry; periodic trend questions (atomic/ionic radius, ionisation energy, electronegativity) are quick, formula-free, and recur every year.",
  pyq:{freq:"1 question most sessions.",historical:"Stable-high as a gateway chapter to p/d-block.",pattern:"Trend comparison across a period/group, anomalous properties, ionisation energy irregularities (e.g., Be>B, N>O).",difficulty:"Easy–Moderate."},
  topics:[{name:"Periodic Trends",priority:1,note:"Atomic radius, ionisation enthalpy, electron gain enthalpy, electronegativity trends and their exceptions — direct comparison question."},
   {name:"Anomalous Properties & Diagonal Relationship",priority:2,note:"Li-Mg, Be-Al diagonal relationships — factual recall question."}],
  mustKnow:["Ionisation enthalpy exceptions: Be>B, N>O, Mg>Al, P>S (extra stability of filled/half-filled subshells).","Electronegativity generally increases across a period, decreases down a group (Pauling scale).","Diagonal relationship pairs: Li–Mg, Be–Al, B–Si."],
  pyqTypes:["Rank a set of elements/ions by radius, ionisation energy, or electronegativity.","Identify the anomalous trend among a set of successive ionisation energies."],
  mistakes:["Forgetting that ionic radius depends on charge, not just position (isoelectronic species comparison).","Missing the half-filled/fully-filled stability exceptions in ionisation energy order."],
  prereq:["Atomic Structure"], connected:["p-Block Elements","d- and f-Block Elements"]},

 {name:"p-Block Elements", priority:1,
  importance:"Historically one of the top chemistry chapters by frequency; substantial descriptive content (noble gases, silicates, sulfur/nitrogen compound details) was trimmed in 2023-24, so current focus is more conceptual/trend-based than pure memorisation.",
  pyq:{freq:"1–2 questions most sessions.",historical:"Consistently top-ranked in most PYQ analyses.",pattern:"Structure/shape of oxoacids and hydrides, anomalous behaviour of first member of a group, trend-based reasoning across groups 13-18.",difficulty:"Moderate."},
  topics:[{name:"Group 13-14 Trends & Compounds",priority:1,note:"Anomalous behaviour of Boron/Carbon vs rest of group; structure of diborane, allotropes of carbon — factual + reasoning."},
   {name:"Group 15-16 Trends & Oxoacids",priority:1,note:"Shapes/structures of oxoacids of phosphorus, hybridisation in compounds like PCl5 — structure-based question."},
   {name:"Group 17-18 (Halogens & Noble Gases, basics)",priority:2,note:"Interhalogen compounds, basic noble gas compound facts (lighter after trimming) — factual recall."}],
  mustKnow:["Anomalous behaviour of the first element of each p-block group (small size, high electronegativity, absence of d-orbitals).","Structures: diborane (banana bonds), XeF-series shapes via VSEPR, common oxoacid structures.","Trend of acidic/basic character of oxides across a period and down a group."],
  pyqTypes:["Identify the correct shape/hybridisation of a given p-block compound.","Reasoning-based statement question on anomalous behaviour of a first-row p-block element."],
  mistakes:["Applying VSEPR incorrectly to expanded-octet p-block compounds.","Missing that many descriptive facts (silicates, specific industrial preparations) are now outside the trimmed syllabus — don't over-invest time memorising deleted detail."],
  prereq:["Periodicity","Chemical Bonding"], connected:["d- and f-Block Elements","Organic Chemistry (some overlap via boron/carbon reagents)"]},

 {name:"d- and f-Block Elements", priority:1,
  importance:"Flagged high (Vedantu 4.69%); colour of transition-metal ions, variable oxidation states, and magnetic properties are recurring factual+reasoning question types.",
  pyq:{freq:"1 question most sessions.",historical:"Stable-high.",pattern:"Variable oxidation states, colour due to d-d transition, magnetic moment calculation, lanthanide contraction and its consequences.",difficulty:"Moderate."},
  topics:[{name:"Variable Oxidation States & Colour",priority:1,note:"Explain colour via d-d transition (needs partially filled d-orbitals); highest oxidation state trend across a series — reasoning question."},
   {name:"Magnetic Properties",priority:1,note:"Spin-only magnetic moment μ=√(n(n+2)) BM from number of unpaired electrons — direct-formula numerical."},
   {name:"Lanthanide Contraction & Consequences",priority:2,note:"Similarity of 4d/5d element radii, effect on basicity of lanthanide hydroxides — factual reasoning."}],
  mustKnow:["Spin-only formula μ=√n(n+2) BM; find n (unpaired electrons) from d-electron count and oxidation state.","Sc³⁺ (d⁰) and Zn²⁺ (d¹⁰) are colourless — no d-d transition possible; classic exception question.","Lanthanide contraction causes near-identical radii of 4d and 5d transition elements in the same group."],
  pyqTypes:["Given a transition metal ion, find its spin-only magnetic moment.","Identify the colourless ion among a list of transition metal ions (d⁰ or d¹⁰ cases)."],
  mistakes:["Forgetting to determine oxidation state correctly before counting d-electrons.","Confusing 'coloured' reasoning: assuming all transition ions are coloured regardless of d-electron count."],
  prereq:["Atomic Structure","Periodicity"], connected:["Coordination Compounds"]},

 {name:"Coordination Compounds", priority:1,
  importance:"Reported as a joint-top chemistry chapter (esaral 9.9%, PW 40 Q cumulative); IUPAC naming, isomerism, and Crystal Field Theory (CFT) based colour/magnetism questions recur every year.",
  pyq:{freq:"1–2 questions most sessions — among the most reliably tested Chemistry chapters.",historical:"Consistently top-ranked across all sources checked.",pattern:"IUPAC nomenclature of complexes, geometrical/optical isomerism, CFT splitting & CFSE, magnetic behaviour/colour via CFT.",difficulty:"Moderate–Hard."},
  topics:[{name:"IUPAC Nomenclature of Coordination Compounds",priority:1,note:"Naming complex cations/anions/neutral complexes correctly with ligand order and oxidation state — direct question."},
   {name:"Isomerism in Coordination Compounds",priority:1,note:"Geometrical (cis-trans, fac-mer) and optical isomerism in octahedral/square planar complexes — identification question."},
   {name:"Crystal Field Theory (CFT)",priority:1,note:"d-orbital splitting in octahedral/tetrahedral fields, high-spin vs low-spin, CFSE calculation — very standard reasoning+numerical."}],
  mustKnow:["Strong field vs weak field ligands (spectrochemical series) determine high-spin/low-spin configuration.","CFSE and pairing energy comparison decides spin state for octahedral d⁴-d⁷ complexes.","Coordination number determines geometry: 4→tetrahedral/square planar, 6→octahedral."],
  pyqTypes:["Given a complex ion, determine IUPAC name, hybridisation, geometry, and magnetic behaviour together.","Identify which of several given complexes shows geometrical/optical isomerism."],
  mistakes:["Wrong ligand naming order (alphabetical) or missing 'ido'/'o' suffix conventions for anionic ligands.","Confusing CFT splitting pattern direction between octahedral (eg above t2g) and tetrahedral (reversed, smaller Δ)."],
  prereq:["d- and f-Block Elements","Chemical Bonding (VBT/hybridisation)"], connected:["d- and f-Block Elements","Organic Chemistry (chelate/ligand analogy, conceptual)"]},
];

const CHEM_ORGANIC = [
 {name:"Purification, Characterisation & Basic Principles of Organic Chemistry (GOC)", priority:2,
  importance:"The conceptual foundation (inductive/resonance/hyperconjugation effects, reaction-intermediate stability) underlies every later organic chapter — low direct weight alone, but essential leverage chapter.",
  pyq:{freq:"0–1 direct question; heavily reused as the reasoning base in Hydrocarbons/Haloalkanes/Carbonyl questions.",historical:"Stable foundational importance.",pattern:"Stability order of carbocations/carbanions/free radicals, inductive/resonance effect comparison, purification technique identification.",difficulty:"Moderate."},
  topics:[{name:"Electronic Effects (Inductive, Resonance, Hyperconjugation)",priority:1,note:"Rank stability of substituted carbocations/carbanions — very frequently reused reasoning tool."},
   {name:"Reaction Intermediates",priority:1,note:"Carbocation/carbanion/free-radical stability order and rearrangement tendency — direct + applied question."}],
  mustKnow:["Stability order: 3°>2°>1° carbocation (hyperconjugation+inductive); reverse trend for carbanions.","+M/-M and +I/-I group classification (e.g., -NO2 is -M and -I; -OH is +M but -I).","Common purification techniques: distillation, crystallisation, chromatography — matched to compound property."],
  pyqTypes:["Rank a series of substituted intermediates by stability.","Identify the correct purification technique for a given mixture based on property difference."],
  mistakes:["Confusing inductive effect (through sigma bonds, distance-dependent) with resonance (through pi system, needs conjugation).","Misapplying hyperconjugation count (number of α-hydrogens) for cation stability."],
  prereq:["Chemical Bonding"], connected:["Hydrocarbons","Haloalkanes & Haloarenes","Aldehydes/Ketones/Carboxylic Acids"]},

 {name:"Hydrocarbons", priority:2,
  importance:"Reaction-mechanism-heavy chapter (Markovnikov/anti-Markovnikov addition, ozonolysis) that's a direct prerequisite for identifying products in later functional-group chapters.",
  pyq:{freq:"1 question most sessions, often as a reaction-sequence/product-identification question.",historical:"Stable-moderate.",pattern:"Addition reactions on alkenes/alkynes with mechanism-based selectivity, ozonolysis product identification, aromatic electrophilic substitution directing effects.",difficulty:"Moderate."},
  topics:[{name:"Addition Reactions on Alkenes/Alkynes",priority:1,note:"Markovnikov vs peroxide-effect (anti-Markovnikov, only for HBr) addition — very standard product-prediction question."},
   {name:"Ozonolysis",priority:1,note:"Reductive ozonolysis of alkenes to identify original alkene from carbonyl products — recurring 'find the starting alkene' question."},
   {name:"Electrophilic Aromatic Substitution (EAS) & Directing Effects",priority:1,note:"Ortho/para vs meta directing groups on benzene ring — product-prediction question."}],
  mustKnow:["Peroxide (Kharasch) effect reverses Markovnikov addition ONLY for HBr, not HCl/HI.","Ozonolysis: C=C → two C=O; count carbons/structure to backtrack the alkene.","Activating groups (–OH,–NH2,–R) are o,p-directing; deactivating groups (–NO2,–CN,–COOH) are m-directing (halogens are deactivating but o,p-directing — classic exception)."],
  pyqTypes:["Given ozonolysis products, deduce the structure of the original alkene/diene.","Given a substituted benzene and a reagent, predict the position of the next substitution."],
  mistakes:["Applying Markovnikov's rule to HBr with peroxide present (must reverse).","Forgetting the halogen exception in EAS directing effects (deactivating but o,p-directing)."],
  prereq:["GOC (electronic effects)"], connected:["Haloalkanes & Haloarenes","Alcohols/Phenols/Ethers"]},

 {name:"Haloalkanes and Haloarenes", priority:2,
  importance:"SN1 vs SN2 mechanism questions are a JEE staple and this chapter is the primary place they're tested with full mechanistic reasoning.",
  pyq:{freq:"1 question most sessions.",historical:"Stable-moderate.",pattern:"SN1 vs SN2 conditions (substrate, nucleophile, solvent), Grignard reagent formation and reaction, Wurtz reaction limitations.",difficulty:"Moderate."},
  topics:[{name:"SN1 vs SN2 Mechanism",priority:1,note:"Rate law dependence, stereochemistry (inversion in SN2, racemisation in SN1), substrate/solvent effect — very frequent comparison question."},
   {name:"Grignard Reagent Reactions",priority:1,note:"Reaction with carbonyl compounds/CO2/epoxides to form alcohols/acids — product-prediction question."}],
  mustKnow:["SN2: 1° substrate, strong nucleophile, polar aprotic solvent, backside attack (inversion).","SN1: 3° substrate, polar protic solvent, carbocation intermediate (racemisation).","Grignard reagents react with any acidic proton (including water/alcohol) before reacting with intended electrophile — must be moisture-free."],
  pyqTypes:["Given substrate/nucleophile/solvent conditions, predict whether SN1 or SN2 dominates and the stereochemical outcome.","Grignard reagent + a given carbonyl/ester/CO2 — predict the final product after hydrolysis."],
  mistakes:["Forgetting Grignard reagents are destroyed by protic solvents/moisture before reacting with the intended substrate.","Mixing up which mechanism gives inversion vs racemisation."],
  prereq:["GOC","Hydrocarbons"], connected:["Alcohols, Phenols and Ethers","Amines"]},

 {name:"Alcohols, Phenols and Ethers", priority:2,
  importance:"Bridges Haloalkanes and Carbonyl chemistry; distinguishing tests (Lucas test, phenol's acidity vs alcohols) are frequently tested factual+reasoning items.",
  pyq:{freq:"1 question most sessions.",historical:"Stable-moderate.",pattern:"Lucas test to distinguish 1°/2°/3° alcohols, relative acidity of phenol vs alcohol vs carboxylic acid, Williamson ether synthesis.",difficulty:"Moderate."},
  topics:[{name:"Distinguishing Tests & Relative Acidity",priority:1,note:"Lucas reagent turbidity-time order (3°>2°>1°); acidity order phenol>water>alcohol (resonance stabilisation of phenoxide) — classic reasoning question."},
   {name:"Williamson Ether Synthesis",priority:2,note:"SN2-based ether formation; limitation with 3° alkyl halides (elimination competes) — mechanism-based question."}],
  mustKnow:["Phenoxide ion is resonance-stabilised, making phenol more acidic than alcohols (but less than carboxylic acids).","Lucas test: 3° alcohol reacts instantly (turbidity immediately), 2° in minutes, 1° needs heating.","Electron-withdrawing substituents on phenol ring increase acidity (further stabilise phenoxide); electron-donating decrease it."],
  pyqTypes:["Rank a set of substituted phenols/alcohols by acidity.","Identify the product and mechanism type for a Williamson ether synthesis with a given alkyl halide."],
  mistakes:["Forgetting substituent effect direction on phenol acidity (EWG increases, EDG decreases).","Using Williamson synthesis with a 3° halide and expecting substitution instead of elimination."],
  prereq:["Haloalkanes and Haloarenes","GOC"], connected:["Aldehydes, Ketones and Carboxylic Acids"]},

 {name:"Aldehydes, Ketones and Carboxylic Acids", priority:1,
  importance:"Reported as the single top-weightage Organic chapter by Vedantu (5.95%) and PW (33 Q); nucleophilic addition mechanisms and named reactions (Aldol, Cannizzaro, HVZ) are dense and highly examinable.",
  pyq:{freq:"1–2 questions most sessions — the most reliably tested Organic chapter.",historical:"Consistently top-ranked in Organic Chemistry across sources.",pattern:"Nucleophilic addition reactivity order, named reactions (Aldol condensation, Cannizzaro, Haloform), carboxylic acid acidity/derivative reactions.",difficulty:"Moderate–Hard."},
  topics:[{name:"Nucleophilic Addition Reactions & Reactivity Order",priority:1,note:"HCHO>other aldehydes>ketones reactivity (steric+electronic); reaction with HCN, NaHSO3, Grignard — very frequent."},
   {name:"Named Reactions: Aldol, Cannizzaro, Haloform",priority:1,note:"Conditions required (α-hydrogen for Aldol/Haloform; no α-H for Cannizzaro) — product-prediction question."},
   {name:"Carboxylic Acid Acidity & Derivative Reactions",priority:1,note:"Substituent effect on acidity, conversion to acid chloride/ester/amide — reasoning + sequence question."}],
  mustKnow:["Cannizzaro reaction needs NO α-hydrogen (self redox to alcohol+acid) — a very common trap/identification question.","Haloform reaction requires a methyl ketone or ethanol-type structure (CH3-CO- or CH3-CH(OH)-).","Carboxylic acid acidity increases with electron-withdrawing substituents, decreases with electron-donating (same logic as phenol)."],
  pyqTypes:["Identify which of several given carbonyl compounds will/won't undergo Cannizzaro or Aldol reaction.","Multi-step conversion question: given a starting carbonyl compound, predict the product after 2-3 reagent steps."],
  mistakes:["Applying Aldol conditions to a compound with no α-hydrogen (won't happen — should recognise Cannizzaro instead).","Reactivity order errors — forgetting steric hindrance reduces ketone reactivity relative to aldehydes."],
  prereq:["Alcohols, Phenols and Ethers","GOC"], connected:["Amines","Biomolecules"]},

 {name:"Amines", priority:2,
  importance:"Basicity-comparison and diazonium-salt reaction questions recur reliably; connects organic nitrogen chemistry to both aromatic substitution and biomolecule chapters.",
  pyq:{freq:"1 question most sessions.",historical:"Stable-moderate.",pattern:"Basicity order (aliphatic vs aromatic amines, substituent effects), diazonium salt reactions (Sandmeyer, coupling), Hofmann bromamide degradation.",difficulty:"Moderate."},
  topics:[{name:"Basicity Order of Amines",priority:1,note:"Aliphatic > NH3 > aromatic amines (in gas phase vs aqueous phase gives different orders) — classic reasoning question with a well-known 'exception' trap."},
   {name:"Diazonium Salt Reactions",priority:1,note:"Sandmeyer (→Cl,Br,CN), Balz-Schiemann (→F), coupling reaction (→azo dye) — product-prediction question."}],
  mustKnow:["Aromatic amine basicity is lowered by resonance delocalisation of the lone pair into the ring.","In aqueous phase, basicity order for methyl amines: 2°>1°>3°>NH3 (solvation effects override inductive-only prediction) — a frequently tested nuance.","Diazonium salts are stable only at low temperature (0–5°C); decompose above that."],
  pyqTypes:["Rank a set of substituted anilines/amines by basicity.","Given a diazonium salt and a specific reagent, predict the substitution product."],
  mistakes:["Using only inductive-effect logic for aqueous basicity order (ignores solvation/steric factors that change the ranking).","Forgetting the low-temperature requirement for diazonium salt stability/reactions."],
  prereq:["Haloalkanes and Haloarenes","GOC"], connected:["Biomolecules"]},

 {name:"Biomolecules", priority:3,
  importance:"Mostly factual/descriptive chapter (carbohydrate/protein/vitamin classification); moderate weight but low calculation burden — efficient to revise close to the exam.",
  pyq:{freq:"0–1 question most sessions.",historical:"Stable-moderate, mostly factual recall.",pattern:"Classification of carbohydrates (mono/di/polysaccharide), types of protein structure, vitamin deficiency diseases, DNA/RNA differences.",difficulty:"Easy."},
  topics:[{name:"Carbohydrates Classification & Reactions",priority:1,note:"Glucose open-chain vs cyclic (Haworth) structure, reducing vs non-reducing sugars — factual + reasoning."},
   {name:"Proteins & Enzymes",priority:2,note:"Primary/secondary/tertiary/quaternary structure, denaturation — factual recall question."},
   {name:"Vitamins & Nucleic Acids",priority:2,note:"Fat-soluble vs water-soluble vitamins and deficiency diseases; DNA vs RNA structural differences — direct factual question."}],
  mustKnow:["Reducing sugars have a free anomeric -OH/aldehyde that can reduce Tollens'/Fehling's reagent (sucrose is non-reducing).","Secondary structure = α-helix/β-sheet (H-bonding); denaturation destroys secondary/tertiary structure, not primary (peptide bonds intact).","DNA has deoxyribose + thymine; RNA has ribose + uracil — a very common direct-recall question."],
  pyqTypes:["Identify reducing vs non-reducing sugar from a list.","Match vitamins to their deficiency disease (a very common direct factual question)."],
  mistakes:["Confusing which vitamin is water-soluble vs fat-soluble (affects deficiency/storage reasoning).","Mixing up DNA/RNA base and sugar differences."],
  prereq:["Aldehydes, Ketones and Carboxylic Acids (functional group recognition)"], connected:["General organic reasoning"]},
];

const MATH = [
 {name:"Sets, Relations and Functions", priority:3,
  importance:"Foundational chapter; direct weight is moderate but the function-property reasoning (domain/range, one-one/onto, composition) reappears inside Calculus questions constantly.",
  pyq:{freq:"1 question most sessions.",historical:"Stable-moderate.",pattern:"Domain/range of a function, types of relations (equivalence relation proof), composition and inverse of functions.",difficulty:"Easy–Moderate."},
  topics:[{name:"Domain & Range of Functions",priority:1,note:"Combination of log/root/trig functions — direct calculation question."},
   {name:"Types of Functions & Composition",priority:2,note:"One-one/onto/bijective determination, fog and gof — reasoning + calculation question."}],
  mustKnow:["Domain restrictions: denominator≠0, expression under even root ≥0, log argument>0.","A function is invertible iff it is bijective (one-one and onto).","Equivalence relation needs reflexive+symmetric+transitive — check all three explicitly."],
  pyqTypes:["Find the domain of a composite function involving log/root/inverse-trig.","Determine whether a given relation is an equivalence relation."],
  mistakes:["Forgetting to intersect ALL domain restrictions in a composite expression.","Confusing onto with one-one when checking bijectivity."],
  prereq:[], connected:["Limits, Continuity & Differentiability","Binomial Theorem (function-based series)"]},

 {name:"Complex Numbers and Quadratic Equations", priority:2,
  importance:"Steady moderate-to-high weight; Argand-plane geometry questions and nature-of-roots reasoning are quick, formula-driven marks.",
  pyq:{freq:"1 question most sessions.",historical:"Stable-moderate-high.",pattern:"Modulus-argument form and De Moivre's theorem, locus problems on Argand plane, nature of roots via discriminant, common roots of two quadratics.",difficulty:"Moderate."},
  topics:[{name:"Argand Plane & Locus Problems",priority:1,note:"|z-z1|=|z-z2| type locus (perpendicular bisector), |z|=k (circle) — geometric-interpretation question."},
   {name:"De Moivre's Theorem & nth Roots",priority:1,note:"Find nth roots of unity/complex number, use in evaluating powers — direct application."},
   {name:"Nature & Location of Roots of Quadratics",priority:2,note:"Discriminant sign, condition for roots to lie in a given interval — reasoning + calculation question."}],
  mustKnow:["z=r(cosθ+isinθ); De Moivre's: zⁿ=rⁿ(cos nθ+i sin nθ).","Sum of nth roots of unity = 0; product = (-1)^(n-1) (for n roots of unity).","For ax²+bx+c=0, condition for both roots > k, < k, or between two numbers (sign of f(k), vertex position, discriminant)."],
  pyqTypes:["Argand-plane locus question described algebraically — identify the geometric curve.","Given a quadratic with a parameter, find the range of the parameter for roots to satisfy a location condition."],
  mistakes:["Forgetting the triangle inequality direction for |z1+z2| vs |z1|+|z2| bounds.","Sign errors in discriminant-based root-location conditions (forgetting to also check vertex/f(k) sign, not just discriminant)."],
  prereq:["Quadratic basics (Class 10-11)"], connected:["Sequence and Series (roots of unity sums)"]},

 {name:"Matrices and Determinants", priority:1,
  importance:"Flagged consistently high (PW: 33 Q); highly formula/property driven, and adjoint/inverse-matrix numericals are a reliable, fast-solving scoring area once matrix properties are memorised.",
  pyq:{freq:"1–2 questions most sessions.",historical:"Consistently top-tier in Algebra across sources.",pattern:"Finding inverse via adjoint, solving a system of linear equations (matrix method / Cramer's rule), properties of determinants, matrix equation A²=A or similar identity proofs.",difficulty:"Moderate–Hard."},
  topics:[{name:"Inverse of a Matrix via Adjoint",priority:1,note:"A⁻¹=adj(A)/|A|; use to solve AX=B systems — very standard numerical."},
   {name:"System of Linear Equations (Cramer's Rule / Consistency)",priority:1,note:"Unique/infinite/no-solution conditions via determinant value — reasoning + calculation question."},
   {name:"Matrix Properties & Special Matrices",priority:2,note:"Symmetric/skew-symmetric decomposition, idempotent/orthogonal matrix identities — property-proof-style question."}],
  mustKnow:["|adj(A)|=|A|ⁿ⁻¹ for n×n matrix; (AB)⁻¹=B⁻¹A⁻¹.","System AX=B: unique solution if |A|≠0; check adj(A)B for infinite/no-solution case when |A|=0.","Every square matrix = symmetric part + skew-symmetric part: A=½(A+Aᵀ)+½(A-Aᵀ)."],
  pyqTypes:["Given a 3×3 matrix with a parameter, find the value(s) for which the system has infinite/no solutions.","Evaluate a matrix expression (like A²-5A+7I) using the Cayley-Hamilton-style identity satisfied by A."],
  mistakes:["Sign errors while computing cofactors for the adjoint matrix.","Confusing the conditions for infinite solutions vs no solution when |A|=0 (must additionally check adj(A)·B)."],
  prereq:["Sets, Relations and Functions (basic algebra)"], connected:["Three Dimensional Geometry (plane equations often use determinants)"]},

 {name:"Permutations and Combinations", priority:2,
  importance:"Reliable moderate-weight chapter; circular permutation and grouping/distribution problems are a recurring standalone question style and also underpin Binomial Theorem and Probability.",
  pyq:{freq:"1 question most sessions.",historical:"Stable-moderate.",pattern:"Arrangements with restrictions (together/not together, distinct/identical objects), circular permutations, distribution of objects into groups.",difficulty:"Moderate."},
  topics:[{name:"Arrangements with Restrictions",priority:1,note:"Letters/objects with repetition, 'together'/'never together' conditions — direct-calculation question."},
   {name:"Combinations & Grouping/Distribution",priority:1,note:"Dividing n distinct objects into groups of given sizes (identical vs distinct groups) — classic careful-counting question."},
   {name:"Circular Permutations",priority:2,note:"n objects around a circle = (n-1)!; with reflection symmetry, divide by 2 — direct-formula question."}],
  mustKnow:["Permutation with repetition of identical items: n!/(p!q!r!...).","'At least one' problems: use complementary counting (total − none).","Distinct groups vs identical groups distribution differ by a factor of (number of groups)!."],
  pyqTypes:["Word-arrangement problem with specific letters required to be together/apart.","Distribute n distinct objects into r identical/distinct groups with given size constraints."],
  mistakes:["Forgetting to divide by group-permutations when groups are identical.","Double-counting or under-counting in 'at least/at most' restriction problems — complementary counting avoids this."],
  prereq:["Sets, Relations and Functions (basic counting)"], connected:["Binomial Theorem","Probability"]},

 {name:"Binomial Theorem", priority:2,
  importance:"Institute sources genuinely disagree on this chapter's priority (PW ranks it high-frequency at 24 Q cumulative; CollegeDekho places it in a lower-priority bucket) — treat it as solidly moderate: master the general term and greatest-term techniques rather than deep-diving every identity.",
  pyq:{freq:"1 question most sessions (Historical/PYQ-based trend — sources disagree on exact frequency tier).",historical:"Mixed signal across sources; consistently appears but ranking varies.",pattern:"General term Tr+1 in an expansion, term independent of x, greatest binomial coefficient/term, sum of binomial coefficients using specific x-substitution.",difficulty:"Moderate."},
  topics:[{name:"General Term & Term Independent of x",priority:1,note:"Tr+1=nCr aⁿ⁻ʳ bʳ; set exponent of x to 0 to find the required term — very standard question."},
   {name:"Sum of Series Using Binomial Coefficients",priority:2,note:"Substitute x=1 or x=-1 in (1+x)ⁿ to derive coefficient-sum identities — technique-based question."}],
  mustKnow:["Middle term: one term if n even, two terms if n odd.","Greatest term/coefficient found by ratio Tr+1/Tr compared to 1.","Multinomial theorem generalisation for (a+b+c)ⁿ expansions (occasionally tested)."],
  pyqTypes:["Find the coefficient of a specific power of x in a given binomial/multinomial expansion.","Evaluate a sum of binomial coefficients (e.g., ΣnCr·r or ΣnCr²) using a standard substitution trick."],
  mistakes:["Off-by-one error in general term index (Tr+1 uses power r, not r+1).","Forgetting to handle negative/fractional exponents differently (infinite series case) when n is not a positive integer."],
  prereq:["Permutations and Combinations"], connected:["Sequence and Series"]},

 {name:"Sequence and Series", priority:1,
  importance:"Flagged high (PW: 26 Q, Vedantu 5.74%); AP-GP mixed numericals and sum-to-n-terms techniques (using difference method / telescoping) are a dependable scoring chapter.",
  pyq:{freq:"1 question most sessions.",historical:"Consistently high-ranked across sources.",pattern:"Sum of a series with mixed AP-GP terms (arithmetico-geometric), sum using nth-term difference method, AM-GM-HM inequality application.",difficulty:"Moderate."},
  topics:[{name:"Arithmetico-Geometric Progression (AGP)",priority:1,note:"Sum of series like 1+3x+5x²+7x³+... — standard 'multiply by common ratio and subtract' technique."},
   {name:"Sum to n Terms via Difference Method",priority:1,note:"When Tn is not a standard AP/GP, find Tn by differences then telescope-sum — recurring technique question."},
   {name:"AM-GM-HM Inequality",priority:2,note:"AM≥GM≥HM, equality iff all terms equal — used in optimisation/inequality-proof questions."}],
  mustKnow:["Standard sums: Σn, Σn², Σn³ formulas — used inside difference-method problems.","AGP sum technique: S - (common ratio)S, then sum the resulting GP.","AM-GM-HM equality condition (all terms equal) is the key to many minimum/maximum value questions."],
  pyqTypes:["Sum of a series whose nth term is a product of an AP term and a GP term (AGP).","Find Tn from a given series with non-obvious pattern, then sum to n terms using the difference method."],
  mistakes:["Errors in reindexing terms while doing the 'S - rS' subtraction for AGP.","Applying AM-GM directly without checking all terms are positive (a stated/implied condition)."],
  prereq:["Complex Numbers (roots of unity sums, related technique)"], connected:["Binomial Theorem","Limits (sum-to-infinity connects to limits of partial sums)"]},

 {name:"Limits, Continuity, Differentiability & Applications of Derivatives", priority:1,
  importance:"Core Calculus chapter, flagged high (Vedantu 5.50%); Application of Derivatives (maxima-minima, tangent-normal, increasing/decreasing) is one of the most consistently tested topics in all of JEE Main Maths.",
  pyq:{freq:"1–2 questions most sessions.",historical:"Consistently high; part of Calculus which is 30-37% of the Maths paper per PW.",pattern:"L'Hôpital-style or standard-limit evaluation, continuity/differentiability at a point (piecewise functions), maxima-minima optimisation, tangent/normal to a curve.",difficulty:"Moderate–Hard."},
  topics:[{name:"Standard Limits & Indeterminate Forms",priority:1,note:"limits of (sinx/x), (1+1/n)ⁿ forms, 0/0 and ∞/∞ via series expansion or L'Hôpital — direct-calculation question."},
   {name:"Continuity & Differentiability of Piecewise Functions",priority:1,note:"Find unknown constants for continuity/differentiability at the junction point — standard technique question."},
   {name:"Maxima-Minima (Applications of Derivatives)",priority:1,note:"Optimisation word problems (maximum area/volume/minimum cost) and finding local max/min via first/second derivative test — very frequent."},
   {name:"Tangent, Normal & Rate of Change",priority:2,note:"Equation of tangent/normal at a point, related-rates problems — standard technique question."}],
  mustKnow:["Standard limit list: limx→0 sinx/x=1, (eˣ-1)/x=1, ln(1+x)/x=1, (1+x)^(1/x)→e.","Rolle's Theorem/LMVT are officially deleted — focus limit/continuity prep on direct evaluation and piecewise-function matching instead.","First derivative test (sign change) and second derivative test (f''(x) sign) for local maxima/minima."],
  pyqTypes:["Piecewise function given — find constants making it continuous and/or differentiable at the junction.","Optimisation word problem — set up a function from given constraints, differentiate, and find the optimum value."],
  mistakes:["Checking only continuity when differentiability is asked (differentiability is the stronger condition and implies continuity, not vice versa).","Forgetting to check the domain/interval boundary in optimisation problems (extrema can occur at endpoints too)."],
  prereq:["Sets, Relations and Functions","Trigonometry (limit identities)"], connected:["Integral Calculus","Differential Equations"]},

 {name:"Integral Calculus (Indefinite, Definite & Area under Curve)", priority:1,
  importance:"Reported as a top overall Maths topic (CollegeDekho: 10-11%, called top chapter in a recent session); definite-integral property tricks and area-under-curve problems are dense, high-yield, and reused inside Differential Equations.",
  pyq:{freq:"1–2 questions most sessions.",historical:"Consistently among the top 2-3 Maths chapters.",pattern:"Definite integral using King's property or other standard properties, integration by parts/substitution for a tricky integrand, area bounded by two curves.",difficulty:"Hard."},
  topics:[{name:"Definite Integral Properties (King's Property etc.)",priority:1,note:"∫₀ᵃf(x)dx=∫₀ᵃf(a-x)dx and similar properties to simplify a hard-looking definite integral — very frequent technique question."},
   {name:"Integration by Parts & Substitution (advanced)",priority:1,note:"ILATE rule, reduction-formula-style repeated integration by parts — standard but calculation-heavy question."},
   {name:"Area Bounded by Curves",priority:1,note:"Area between two curves/a curve and a line, using definite integration with correct limits from intersection points — very common."},
   {name:"Note: 'Integral as limit of a sum' is officially deleted",priority:3,note:"Do not spend prep time on the Riemann-sum definition approach; focus on properties/substitution/area applications instead."}],
  mustKnow:["Standard definite-integral properties (period, symmetry about a-x or -x) to collapse a seemingly-hard integral.","ILATE priority order for choosing 'u' in integration by parts.","Area = ∫(upper curve − lower curve)dx between correctly identified intersection limits."],
  pyqTypes:["A definite integral of an oddly-symmetric function — solve using property tricks rather than brute-force integration.","Find area enclosed between a parabola and a line/another curve."],
  mistakes:["Wrong limits or wrong 'upper minus lower' order when computing bounded area (leads to negative/wrong area).","Attempting brute-force integration of an integral clearly designed for a property-based shortcut, wasting time."],
  prereq:["Limits, Continuity & Differentiability","Trigonometric identities"], connected:["Differential Equations","Applications of Derivatives"]},

 {name:"Differential Equations", priority:2,
  importance:"Flagged high by PW (24 Q); variable-separable and linear first-order DE numericals are formulaic once the standard integrating-factor method is internalised.",
  pyq:{freq:"1 question most sessions.",historical:"Stable-high.",pattern:"Forming a differential equation from a given family of curves, solving variable-separable/linear/homogeneous first-order DEs, using an integrating factor.",difficulty:"Moderate–Hard."},
  topics:[{name:"Linear First-Order DE & Integrating Factor",priority:1,note:"dy/dx+Py=Q; IF=e^∫Pdx — very standard solving-technique question."},
   {name:"Variable Separable & Homogeneous DEs",priority:1,note:"Substitution y=vx for homogeneous equations — recurring technique question."},
   {name:"Formation of Differential Equations",priority:2,note:"Eliminate arbitrary constants from a family of curves to get the DE — direct technique question."}],
  mustKnow:["Order = highest derivative present; degree = power of the highest derivative (after removing radicals/fractions).","Integrating factor formula and how to apply it to get the general solution.","Homogeneous DE recognised when dy/dx = f(y/x) — substitute y=vx, dy/dx=v+x(dv/dx)."],
  pyqTypes:["Solve a given first-order linear DE and find a particular solution using an initial condition.","Form the differential equation representing a given family of curves (e.g., all circles through the origin)."],
  mistakes:["Forgetting the constant of integration when finding the integrating factor's exponent.","Misidentifying a DE as homogeneous when it isn't truly expressible as f(y/x)."],
  prereq:["Integral Calculus"], connected:["Applications of Derivatives (rate problems)"]},

 {name:"Coordinate Geometry (Straight Lines, Circle, Parabola, Ellipse, Hyperbola)", priority:2,
  importance:"A large combined unit with mixed internal priority — Circle and Straight Lines are consistently tested, while some sources (CollegeDekho) flag individual conic sections (Parabola/Ellipse/Hyperbola area/tangent-normal problems) as comparatively lower-yield standalone questions.",
  pyq:{freq:"1–2 questions most sessions across the sub-topics combined.",historical:"Straight Lines/Circle stable-moderate-high; individual conics more variable (Historical/PYQ-based trend, disagreement across sources).",pattern:"Family of lines / angle bisector type problems are deleted — focus shifts to circle tangent/chord problems and standard conic tangent-normal equations.",difficulty:"Moderate."},
  topics:[{name:"Circle: Tangent, Chord & Family of Circles",priority:1,note:"Equation of tangent from an external point, condition for a line to be tangent to a circle — very standard numerical."},
   {name:"Parabola/Ellipse/Hyperbola: Standard Properties",priority:2,note:"Focus-directrix property, equation of tangent/normal at a point, eccentricity-based questions — moderate frequency, disputed priority across sources."},
   {name:"Straight Lines: Pair of Lines & Angle Between Them",priority:2,note:"Pair of straight lines through origin (homogeneous 2nd-degree equation), angle between them — direct-formula question."}],
  mustKnow:["Condition for tangency: perpendicular distance from centre to line = radius.","Standard forms and eccentricity formulas for parabola (e=1), ellipse (e<1), hyperbola (e>1).","Note: translation of axes and family-of-lines-through-intersection are officially deleted — don't prepare those techniques."],
  pyqTypes:["Find the equation of a common tangent to two circles, or a tangent from an external point.","Given eccentricity/focus/directrix conditions, find the equation of a conic or a specific chord/tangent."],
  mistakes:["Sign errors in the general conic tangent/normal formulas when the conic isn't in the simplest standard position.","Forgetting circle-tangency condition must use perpendicular (not any) distance from the centre."],
  prereq:["Complex Numbers (locus link)","Quadratic Equations"], connected:["Three Dimensional Geometry","Vector Algebra"]},

 {name:"Three Dimensional Geometry", priority:1,
  importance:"Reported as the single top Maths chapter by multiple sources (PW: 35 Q; Vedantu: 7.35% — top math chapter); shortest-distance-between-lines and plane-equation numericals are highly formulaic and dependable.",
  pyq:{freq:"1–2 questions most sessions — the most reliably tested Maths chapter.",historical:"Consistently #1 or top-2 across nearly every source.",pattern:"Shortest distance between two skew lines, equation of a plane through given conditions, angle between line-plane or plane-plane, foot of perpendicular from a point to a line/plane.",difficulty:"Moderate."},
  topics:[{name:"Shortest Distance Between Two Lines",priority:1,note:"Skew-line distance formula using direction vectors and a connecting vector (via determinant/cross product) — very standard numerical."},
   {name:"Equation of a Plane (various conditions)",priority:1,note:"Plane through 3 points, plane containing a line and a point, angle between two planes — very frequent."},
   {name:"Direction Cosines/Ratios & Angle Between Lines",priority:2,note:"Angle between two lines via direction ratios — direct-formula question."}],
  mustKnow:["Shortest distance between skew lines formula (using the box/determinant product of direction vectors and connecting vector).","General plane equation ax+by+cz=d; angle between planes via normal vectors' dot product.","Foot of perpendicular from a point to a line/plane — parametrise and use the perpendicularity condition."],
  pyqTypes:["Find the shortest distance between two given skew lines (very frequently recurring exact question type).","Find the equation of a plane satisfying a combination of point/line/perpendicularity conditions."],
  mistakes:["Arithmetic slips in the 3×3 determinant used for shortest-distance/plane-equation formulas.","Confusing direction ratios with direction cosines (cosines must be normalised, ratios need not be)."],
  prereq:["Vector Algebra","Matrices and Determinants"], connected:["Vector Algebra","Coordinate Geometry"]},

 {name:"Vector Algebra", priority:2,
  importance:"Feeds directly into Three-Dimensional Geometry; scalar/vector triple product is officially deleted, so current focus is dot/cross product applications and vector-geometry proofs.",
  pyq:{freq:"1 question most sessions, often blended with 3D Geometry.",historical:"Stable-moderate.",pattern:"Projection of one vector on another, area of a triangle/parallelogram via cross product, unit vector along a given direction, vector equation of a line.",difficulty:"Moderate."},
  topics:[{name:"Dot & Cross Product Applications",priority:1,note:"Angle between vectors, area of triangle/parallelogram, projection formula — very standard numerical."},
   {name:"Vector Equation of a Line/Plane",priority:2,note:"r=a+λb form and conversion to Cartesian — direct technique question."}],
  mustKnow:["a·b=|a||b|cosθ; a×b gives a vector perpendicular to both with magnitude |a||b|sinθ.","Scalar/vector triple product is officially deleted — don't invest prep time in box-product identities beyond their use inside 3D-geometry shortest-distance formulas.","Projection of a on b = (a·b)/|b|."],
  pyqTypes:["Find the area of a triangle/parallelogram given two side vectors.","Find a unit vector perpendicular to two given vectors (via cross product) satisfying an extra condition."],
  mistakes:["Confusing dot product (scalar) output with cross product (vector) output in formula application.","Sign/order errors in cross product (a×b=-b×a) affecting direction-dependent answers."],
  prereq:["Basic 2D vectors (Physics overlap)"], connected:["Three Dimensional Geometry"]},

 {name:"Statistics and Probability", priority:2,
  importance:"Flagged as consistently moderate-to-high (CollegeDekho: 8-10%); Bayes' theorem and conditional-probability numericals are a reliable standalone question type, though Bernoulli-trial binomial-distribution detail is officially deleted.",
  pyq:{freq:"1 question most sessions.",historical:"Stable-moderate-high.",pattern:"Conditional probability and Bayes' theorem word problems, mean/variance/standard deviation of grouped data, probability using combinatorics (cards/dice/balls).",difficulty:"Moderate."},
  topics:[{name:"Conditional Probability & Bayes' Theorem",priority:1,note:"P(A|B) and total-probability/Bayes' word problems (defective items, disease testing scenarios) — very standard numerical."},
   {name:"Mean, Variance & Standard Deviation (grouped data)",priority:1,note:"Direct/shortcut/step-deviation method for grouped frequency data — calculation-heavy but formulaic."},
   {name:"Note: Bernoulli Trials & Binomial Distribution officially deleted",priority:3,note:"Don't prepare binomial-distribution-specific numericals (P(X=r)=nCr pʳ qⁿ⁻ʳ) as a dedicated topic — focus on classical probability and Bayes' instead."}],
  mustKnow:["Bayes' theorem: P(Ai|B)=P(B|Ai)P(Ai)/ΣP(B|Aj)P(Aj).","Variance = E(X²)-[E(X)]²; standard deviation is its square root.","Independent events: P(A∩B)=P(A)P(B); mutually exclusive events: P(A∩B)=0 (don't confuse the two conditions)."],
  pyqTypes:["Multi-stage probability word problem (e.g., item from one of several boxes, found defective — find source-box probability via Bayes').","Find variance/mean of a grouped frequency distribution using the step-deviation method."],
  mistakes:["Confusing independent and mutually exclusive event conditions.","Arithmetic slips in step-deviation method (forgetting to multiply back by class width and add the assumed mean)."],
  prereq:["Permutations and Combinations","Sets, Relations and Functions"], connected:["Sequence and Series (mean/variance formulas)"]},

 {name:"Trigonometry (Ratios, Identities & Equations)", priority:3,
  importance:"Historically the smallest Maths sub-discipline by weight (~5-7% per multiple sources); Heights & Distances is officially deleted and Properties of a Triangle is flagged as the single lowest-weight chapter (Vedantu: 0.36%) — prioritise trigonometric equations/identities over triangle-property depth.",
  pyq:{freq:"0–1 question most sessions, often blended into another chapter's question as an identity step.",historical:"Consistently the lowest-weight Maths sub-discipline.",pattern:"Solving trigonometric equations for general solution, proving/using compound-angle identities, occasional inverse-trig-function domain/range question.",difficulty:"Easy–Moderate."},
  topics:[{name:"Trigonometric Equations (general solution)",priority:1,note:"Solve equations like sinθ=k or a cosθ+b sinθ=c for general solution — direct technique question."},
   {name:"Inverse Trigonometric Functions",priority:2,note:"Domain/range/principal value branch, simplification of compound inverse-trig expressions — factual + calculation question."},
   {name:"Properties of a Triangle & Heights and Distances",priority:4,note:"Officially, Heights & Distances is deleted from JEE Main; Properties of a Triangle (sine/cosine rule) is the lowest-flagged Maths chapter — treat as optional/last-priority revision only."}],
  mustKnow:["General solution forms: sinθ=sinα → θ=nπ+(-1)ⁿα; cosθ=cosα → θ=2nπ±α; tanθ=tanα → θ=nπ+α.","Principal value branches for sin⁻¹,cos⁻¹,tan⁻¹ and their domain/range.","Compound angle formulas (sin/cos of A±B) used to simplify equations before solving."],
  pyqTypes:["Solve a trigonometric equation over a given interval and count/identify solutions.","Simplify or evaluate a compound inverse-trigonometric expression."],
  mistakes:["Missing solution branches (forgetting the ± or (-1)ⁿ factor) when writing the general solution.","Confusing principal value range for inverse-trig functions with the general solution range."],
  prereq:["Basic trigonometric ratios (Class 10-11)"], connected:["Limits (standard trig limits)","Complex Numbers (De Moivre's theorem)"]},
];

module.exports = { PHYSICS, CHEM_PHYSICAL, CHEM_INORGANIC, CHEM_ORGANIC, MATH };
